
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:26:45 IST (Feb 28 2026 09:56:45 UTC)

// Verification Directory fv/auto_comparator2 

module auto_comparator2(clk, rst, en, a, b, max_val, max_idx);
  input clk, rst, en;
  input [15:0] a, b;
  output [15:0] max_val;
  output [7:0] max_idx;
  wire clk, rst, en;
  wire [15:0] a, b;
  wire [15:0] max_val;
  wire [7:0] max_idx;
  wire n_11, n_41, n_82, n_84, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_100, n_101, n_102, n_103, n_104;
  wire n_141, n_212, n_213, n_219, n_235, n_236, n_242, n_244;
  wire n_249, n_255, n_261, n_264, n_270, n_286, n_296, n_298;
  wire n_303, n_309, n_310, n_328, n_329, n_332, n_334, n_345;
  wire n_356, n_390, n_396, n_411, n_462, n_463, n_464, n_465;
  wire n_467, n_471, n_472, n_476, n_491, n_513, n_515, n_538;
  wire n_540, n_543, n_555, n_568, n_570, n_576, n_599, n_600;
  wire n_601, n_602, n_613, n_614, n_616, n_629, n_640, n_641;
  wire n_655, n_657, n_658, n_664, n_665, n_670, n_671, n_675;
  wire n_676, n_677, n_678, n_698, n_699, n_707, n_729, n_734;
  wire n_736, n_737, n_739, n_741, n_742, n_747, n_748, n_750;
  wire n_752, n_775, n_778, n_779, n_795, n_796, n_797, n_798;
  wire n_800, n_803, n_804, n_805, n_811, n_813, n_814, n_817;
  wire n_819, n_821, n_822, n_823, n_839, n_841, n_843, n_844;
  wire n_845, n_846, n_848, n_850, n_851, n_852, n_854, n_855;
  wire n_856, n_857, n_858, n_861, n_863, n_865, n_866, n_867;
  wire n_868, n_869, n_870, n_871, n_878, n_879, n_880, n_881;
  wire n_882, n_884, n_885, n_886, n_887, n_888, n_889, n_894;
  wire n_895, n_896, n_897, n_898, n_899, n_900, n_901, n_905;
  wire n_908, n_909, n_913, n_914, n_915, n_918, n_919, n_925;
  wire n_926, n_927, n_928, n_929, n_933, n_934, n_936, n_937;
  wire n_938, n_939, n_940, n_945, n_947, n_948, n_949, n_974;
  assign max_idx[2] = 1'b0;
  assign max_idx[3] = 1'b0;
  assign max_idx[4] = 1'b0;
  assign max_idx[5] = 1'b0;
  assign max_idx[6] = 1'b0;
  assign max_idx[7] = 1'b0;
  DFFHQX1 \max_val_reg[0] (.CK (clk), .D (n_310), .Q (max_val[0]));
  DFFHQX1 \max_val_reg[1] (.CK (clk), .D (n_919), .Q (max_val[1]));
  DFFHQX1 \max_val_reg[2] (.CK (clk), .D (n_940), .Q (max_val[2]));
  DFFHQX1 \max_val_reg[3] (.CK (clk), .D (n_411), .Q (max_val[3]));
  DFFHQX1 \max_val_reg[4] (.CK (clk), .D (n_309), .Q (max_val[4]));
  DFFHQX1 \max_val_reg[5] (.CK (clk), .D (n_576), .Q (max_val[5]));
  DFFHQX1 \max_val_reg[6] (.CK (clk), .D (n_670), .Q (max_val[6]));
  DFFHQX1 \max_val_reg[7] (.CK (clk), .D (n_296), .Q (max_val[7]));
  DFFHQX1 \max_val_reg[8] (.CK (clk), .D (n_543), .Q (max_val[8]));
  DFFHQX1 \max_val_reg[9] (.CK (clk), .D (n_641), .Q (max_val[9]));
  DFFHQX1 \max_val_reg[10] (.CK (clk), .D (n_396), .Q (max_val[10]));
  DFFHQX1 \max_val_reg[11] (.CK (clk), .D (n_914), .Q (max_val[11]));
  DFFHQX1 \max_val_reg[12] (.CK (clk), .D (n_752), .Q (max_val[12]));
  DFFHQX1 \max_val_reg[13] (.CK (clk), .D (n_303), .Q (max_val[13]));
  DFFHQX1 \max_val_reg[14] (.CK (clk), .D (n_298), .Q (max_val[14]));
  DFFHQX1 \max_val_reg[15] (.CK (clk), .D (n_909), .Q (max_val[15]));
  DFFHQX4 \max_idx_reg[0] (.CK (clk), .D (n_947), .Q (max_idx[0]));
  DFFHQX4 \max_idx_reg[1] (.CK (clk), .D (n_141), .Q (max_idx[1]));
  NAND2X2 g3548__7482(.A (n_103), .B (n_938), .Y (n_141));
  NAND2X1 g3584__6131(.A (max_val[3]), .B (n_102), .Y (n_104));
  NAND2X1 g3579__1881(.A (max_idx[1]), .B (n_102), .Y (n_103));
  NAND2X1 g3580__5115(.A (max_val[0]), .B (n_102), .Y (n_101));
  NAND2X1 g3581__7482(.A (max_val[14]), .B (n_102), .Y (n_100));
  NAND2X1 g3585__9945(.A (max_val[4]), .B (n_102), .Y (n_94));
  NAND2X1 g3586__2883(.A (max_val[6]), .B (n_102), .Y (n_93));
  NAND2X1 g3587__2346(.A (max_val[5]), .B (n_102), .Y (n_92));
  NAND2X1 g3588__1666(.A (max_val[12]), .B (n_102), .Y (n_91));
  NAND2X1 g3589__7410(.A (max_val[9]), .B (n_102), .Y (n_90));
  NAND2X1 g3590__6417(.A (max_val[7]), .B (n_102), .Y (n_89));
  NAND2X1 g3591__5477(.A (max_val[8]), .B (n_102), .Y (n_88));
  NAND2X1 g3596__4319(.A (max_val[13]), .B (n_102), .Y (n_84));
  NAND2X1 g3598__5526(.A (max_val[10]), .B (n_102), .Y (n_82));
  NOR2X8 g3616__2883(.A (en), .B (rst), .Y (n_102));
  CLKAND2X6 g3622__6417(.A (n_236), .B (b[0]), .Y (n_41));
  INVX1 g3629(.A (rst), .Y (n_11));
  INVX20 fopt3717(.A (a[13]), .Y (n_212));
  INVX2 fopt3718(.A (a[4]), .Y (n_213));
  INVX2 fopt3729(.A (a[0]), .Y (n_235));
  INVX16 fopt3730(.A (a[0]), .Y (n_236));
  INVX2 fopt3734(.A (a[8]), .Y (n_244));
  INVX2 fopt3739(.A (a[3]), .Y (n_249));
  INVX1 fopt3744(.A (b[0]), .Y (n_255));
  INVX4 fopt3751(.A (n_729), .Y (n_264));
  OAI221X4 g3536__3776(.A0 (n_332), .A1 (n_329), .B0 (n_270), .B1
       (n_938), .C0 (n_89), .Y (n_296));
  OAI221X4 g3544__3777(.A0 (n_599), .A1 (n_936), .B0 (n_334), .B1
       (n_938), .C0 (n_100), .Y (n_298));
  OAI221X4 g3542__3783(.A0 (n_212), .A1 (n_329), .B0 (n_242), .B1
       (n_938), .C0 (n_84), .Y (n_303));
  OAI221X4 g3529__3789(.A0 (n_213), .A1 (n_936), .B0 (n_570), .B1
       (n_938), .C0 (n_94), .Y (n_309));
  OAI221X4 g3533__3790(.A0 (n_235), .A1 (n_936), .B0 (n_255), .B1
       (n_938), .C0 (n_101), .Y (n_310));
  INVX20 fopt3806(.A (n_328), .Y (n_329));
  CLKAND2X12 g3550__3774_dup(.A (n_513), .B (n_676), .Y (n_328));
  INVX2 fopt3807(.A (a[7]), .Y (n_332));
  INVX1 g3815(.A (a[5]), .Y (n_345));
  INVX20 g3826(.A (a[1]), .Y (n_356));
  INVX2 fopt3860(.A (a[10]), .Y (n_390));
  OAI221X4 g3539__3866(.A0 (n_390), .A1 (n_936), .B0 (n_602), .B1
       (n_938), .C0 (n_82), .Y (n_396));
  OAI221X4 g3532__3880(.A0 (n_249), .A1 (n_329), .B0 (n_467), .B1
       (n_938), .C0 (n_104), .Y (n_411));
  INVX20 fopt3921(.A (b[7]), .Y (n_270));
  NAND2X4 g3619__3926(.A (a[3]), .B (n_462), .Y (n_463));
  INVX20 g3927(.A (b[3]), .Y (n_462));
  NOR2X8 g3627__3928(.A (a[3]), .B (n_462), .Y (n_464));
  INVX20 g3878_dup(.A (b[3]), .Y (n_465));
  BUFX2 g3930(.A (n_465), .Y (n_467));
  NOR2X2 g36(.A (a[15]), .B (n_471), .Y (n_472));
  INVX8 fopt(.A (b[15]), .Y (n_471));
  NOR2X2 g37(.A (n_599), .B (b[14]), .Y (n_476));
  INVX16 fopt68(.A (b[11]), .Y (n_491));
  CLKAND2X12 g17(.A (n_513), .B (n_676), .Y (n_515));
  AND2X4 g19(.A (en), .B (n_11), .Y (n_513));
  NOR2X8 g102(.A (a[8]), .B (n_856), .Y (n_538));
  INVX3 g101(.A (n_538), .Y (n_540));
  OAI221X4 g98(.A0 (n_244), .A1 (n_329), .B0 (n_856), .B1 (n_938), .C0
       (n_88), .Y (n_543));
  NOR2X4 g171(.A (n_270), .B (n_863), .Y (n_555));
  INVX16 fopt3940(.A (b[5]), .Y (n_568));
  OAI221X4 g94(.A0 (n_345), .A1 (n_329), .B0 (n_823), .B1 (n_938), .C0
       (n_92), .Y (n_576));
  INVX20 fopt110(.A (b[4]), .Y (n_570));
  INVX20 fopt3946(.A (b[14]), .Y (n_334));
  INVX8 fopt38(.A (a[14]), .Y (n_599));
  INVX16 g4(.A (n_600), .Y (n_601));
  INVX20 g3949(.A (b[10]), .Y (n_600));
  INVXL g9(.A (n_601), .Y (n_602));
  OAI21X4 g425(.A0 (n_476), .A1 (n_472), .B0 (n_778), .Y (n_613));
  OR2X4 g427(.A (n_212), .B (b[13]), .Y (n_614));
  INVX6 g430(.A (n_212), .Y (n_616));
  INVX8 g431(.A (b[13]), .Y (n_242));
  INVX6 g3955(.A (a[7]), .Y (n_629));
  OAI221X4 g3963(.A0 (n_219), .A1 (n_329), .B0 (n_640), .B1 (n_938),
       .C0 (n_90), .Y (n_641));
  INVX1 fopt3964(.A (b[9]), .Y (n_640));
  NOR2X8 g268(.A (n_845), .B (n_814), .Y (n_655));
  NOR2X8 g266(.A (n_678), .B (n_657), .Y (n_658));
  INVX3 g267(.A (n_655), .Y (n_657));
  AOI21X4 g3965(.A0 (a[6]), .A1 (n_664), .B0 (a[7]), .Y (n_665));
  INVX16 fopt126(.A (b[6]), .Y (n_664));
  OAI221X4 g114(.A0 (n_261), .A1 (n_329), .B0 (n_664), .B1 (n_938), .C0
       (n_93), .Y (n_670));
  NAND2X8 g71(.A (n_675), .B (n_655), .Y (n_676));
  NOR2X8 g73(.A (n_671), .B (n_882), .Y (n_675));
  NAND2X8 g78(.A (n_613), .B (n_871), .Y (n_671));
  NAND2X8 g72(.A (n_513), .B (n_677), .Y (n_678));
  NOR2X8 g74(.A (n_671), .B (n_882), .Y (n_677));
  INVX4 g1(.A (n_698), .Y (n_699));
  INVX16 g3(.A (b[9]), .Y (n_698));
  INVX16 fopt3985(.A (b[1]), .Y (n_707));
  INVX16 fopt3999(.A (a[2]), .Y (n_729));
  NAND2X4 g12(.A (b[6]), .B (n_261), .Y (n_734));
  NAND2X6 g14(.A (n_737), .B (n_219), .Y (n_739));
  INVX4 g4003(.A (n_736), .Y (n_737));
  INVX16 g4004(.A (b[9]), .Y (n_736));
  INVX20 g4005(.A (a[9]), .Y (n_219));
  NAND2X4 g15(.A (n_219), .B (n_699), .Y (n_741));
  NOR2X6 g80(.A (n_747), .B (n_865), .Y (n_748));
  NOR2X4 g82(.A (a[12]), .B (n_286), .Y (n_747));
  CLKINVX12 g2(.A (a[12]), .Y (n_742));
  INVX20 g4009(.A (b[12]), .Y (n_286));
  OR2X4 g81(.A (b[12]), .B (n_742), .Y (n_750));
  OAI221X4 g4011(.A0 (n_742), .A1 (n_936), .B0 (n_286), .B1 (n_938),
       .C0 (n_91), .Y (n_752));
  NOR2X4 g48(.A (n_868), .B (n_839), .Y (n_775));
  NAND2X2 g50(.A (a[15]), .B (n_471), .Y (n_778));
  NOR3X8 g47(.A (n_839), .B (n_538), .C (n_865), .Y (n_779));
  NOR2X8 g11(.A (n_795), .B (n_601), .Y (n_796));
  CLKINVX12 fopt4035(.A (a[10]), .Y (n_795));
  NOR2X6 g4037(.A (n_798), .B (n_899), .Y (n_800));
  INVX3 g53(.A (n_797), .Y (n_798));
  NAND2X6 g54(.A (n_900), .B (n_601), .Y (n_797));
  NAND3X8 g4038(.A (n_797), .B (n_540), .C (n_897), .Y (n_803));
  INVX6 fopt4039(.A (a[1]), .Y (n_804));
  INVX3 fopt183(.A (n_707), .Y (n_805));
  NOR3X8 g59(.A (n_803), .B (n_878), .C (n_813), .Y (n_814));
  NOR2X6 g60(.A (n_811), .B (n_822), .Y (n_813));
  NOR2X6 g4040(.A (n_665), .B (n_555), .Y (n_811));
  NOR2X6 g4041(.A (n_949), .B (n_821), .Y (n_822));
  NAND2X6 g4043(.A (n_817), .B (n_887), .Y (n_821));
  OR2X6 g4044(.A (a[5]), .B (n_568), .Y (n_817));
  NAND2X8 g4047(.A (a[4]), .B (n_570), .Y (n_819));
  INVX6 fopt4048(.A (b[5]), .Y (n_823));
  NOR2X6 g61(.A (n_867), .B (b[15]), .Y (n_839));
  NOR3X8 g105(.A (n_854), .B (n_841), .C (n_844), .Y (n_845));
  NAND2X8 g108(.A (n_779), .B (n_800), .Y (n_841));
  NAND2X8 g107(.A (n_974), .B (n_843), .Y (n_844));
  NOR2X8 g110(.A (n_948), .B (n_885), .Y (n_843));
  AOI21X4 g304(.A0 (n_846), .A1 (n_852), .B0 (n_889), .Y (n_854));
  OAI21X4 g307(.A0 (n_804), .A1 (n_805), .B0 (n_41), .Y (n_846));
  NOR3X8 g305(.A (n_934), .B (n_848), .C (n_851), .Y (n_852));
  NOR2X8 g308(.A (n_465), .B (a[3]), .Y (n_848));
  NOR2X6 g310(.A (n_707), .B (n_850), .Y (n_851));
  INVX8 fopt313(.A (n_356), .Y (n_850));
  AOI22X4 g4060(.A0 (a[9]), .A1 (n_855), .B0 (n_856), .B1 (a[8]), .Y
       (n_857));
  INVX8 fopt4061(.A (b[9]), .Y (n_855));
  INVX16 fopt4062(.A (b[8]), .Y (n_856));
  NAND2X6 g4063(.A (n_741), .B (n_901), .Y (n_858));
  NOR3X6 g21(.A (b[6]), .B (n_861), .C (n_261), .Y (n_863));
  INVX8 fopt4065(.A (a[7]), .Y (n_861));
  INVX20 fopt26(.A (a[6]), .Y (n_261));
  NAND3X6 g4066(.A (n_866), .B (n_869), .C (n_870), .Y (n_871));
  INVX4 g4067(.A (n_865), .Y (n_866));
  NOR2X8 g4068(.A (n_242), .B (n_616), .Y (n_865));
  AOI2BB1X4 g4069(.A0N (n_867), .A1N (b[15]), .B0 (n_868), .Y (n_869));
  INVX16 fopt4070(.A (a[15]), .Y (n_867));
  NOR2X6 g4071(.A (a[14]), .B (n_334), .Y (n_868));
  NAND2X8 g4072(.A (n_614), .B (n_750), .Y (n_870));
  NOR2X8 g145(.A (n_878), .B (n_881), .Y (n_882));
  NAND2X8 g148(.A (n_775), .B (n_748), .Y (n_878));
  NOR2X8 g146(.A (n_879), .B (n_880), .Y (n_881));
  NOR2X6 g149(.A (n_927), .B (n_929), .Y (n_879));
  NOR3X8 g147(.A (n_858), .B (n_857), .C (n_896), .Y (n_880));
  NAND2X8 g7(.A (n_884), .B (n_945), .Y (n_885));
  OR2X6 g4076(.A (a[4]), .B (n_570), .Y (n_884));
  NAND2X8 g4077(.A (n_886), .B (n_819), .Y (n_887));
  NAND2X8 g4078(.A (a[5]), .B (n_568), .Y (n_886));
  OAI21X4 g27(.A0 (n_464), .A1 (n_888), .B0 (n_463), .Y (n_889));
  NAND2X6 g4079(.A (n_937), .B (n_264), .Y (n_888));
  INVX2 g4083(.A (n_895), .Y (n_896));
  NAND2X6 g4084(.A (b[11]), .B (n_894), .Y (n_895));
  INVX20 fopt4085(.A (a[11]), .Y (n_894));
  CLKAND2X6 g4086(.A (n_739), .B (n_895), .Y (n_897));
  NAND2X8 g4087(.A (n_898), .B (n_739), .Y (n_899));
  NAND2X6 g8_dup(.A (b[11]), .B (n_894), .Y (n_898));
  NAND2X4 g8(.A (n_900), .B (n_601), .Y (n_901));
  INVX12 fopt4088(.A (a[10]), .Y (n_900));
  OAI221X4 g52(.A0 (n_905), .A1 (n_936), .B0 (n_471), .B1 (n_938), .C0
       (n_908), .Y (n_909));
  CLKINVX2 fopt4091(.A (a[15]), .Y (n_905));
  NAND2X1 g4092(.A (max_val[15]), .B (n_102), .Y (n_908));
  OAI221X4 g4093(.A0 (n_926), .A1 (n_936), .B0 (n_491), .B1 (n_938),
       .C0 (n_913), .Y (n_914));
  NAND2X1 g4097(.A (max_val[11]), .B (n_102), .Y (n_913));
  OAI221X4 g4098(.A0 (n_915), .A1 (n_936), .B0 (n_707), .B1 (n_938),
       .C0 (n_918), .Y (n_919));
  BUFX2 g6(.A (n_356), .Y (n_915));
  NAND2X1 g4101(.A (max_val[1]), .B (n_102), .Y (n_918));
  INVX1 g4106(.A (n_925), .Y (n_926));
  BUFX6 fopt4107(.A (a[11]), .Y (n_925));
  NOR2X4 g4108(.A (n_925), .B (n_796), .Y (n_927));
  AOI21X4 g4109(.A0 (n_928), .A1 (n_796), .B0 (n_491), .Y (n_929));
  BUFX6 fopt3967_dup(.A (a[11]), .Y (n_928));
  NOR2X8 g4111(.A (a[2]), .B (n_933), .Y (n_934));
  INVX16 fopt4112(.A (b[2]), .Y (n_933));
  OAI221X4 g4113(.A0 (n_729), .A1 (n_936), .B0 (n_937), .B1 (n_938),
       .C0 (n_939), .Y (n_940));
  INVX20 g58(.A (n_515), .Y (n_936));
  INVX8 fopt4114(.A (b[2]), .Y (n_937));
  INVX20 g4115(.A (n_658), .Y (n_938));
  NAND2X1 g4116(.A (max_val[2]), .B (n_102), .Y (n_939));
  OR2X6 g4121(.A (a[14]), .B (n_334), .Y (n_945));
  OAI2BB1X4 g4123(.A0N (max_idx[0]), .A1N (n_102), .B0 (n_329), .Y
       (n_947));
  OAI22X4 g4124(.A0 (n_270), .A1 (a[7]), .B0 (n_664), .B1 (a[6]), .Y
       (n_948));
  OAI2BB1X4 g4125(.A0N (n_629), .A1N (b[7]), .B0 (n_734), .Y (n_949));
  OA22X4 g4137(.A0 (a[12]), .A1 (n_286), .B0 (n_823), .B1 (a[5]), .Y
       (n_974));
endmodule

