
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:49:19 IST (Feb 28 2026 10:19:19 UTC)

// Verification Directory fv/downcounter_16bit 

module downcounter_16bit(clk, rst, load, en_cnt, load_value, CTR_OUT);
  input clk, rst, load, en_cnt;
  input [15:0] load_value;
  output CTR_OUT;
  wire clk, rst, load, en_cnt;
  wire [15:0] load_value;
  wire CTR_OUT;
  wire [15:0] count;
  wire n_9, n_18, n_24, n_25, n_36, n_44, n_50, n_84;
  wire n_123, n_131, n_132, n_134, n_136, n_138, n_158, n_289;
  wire n_316, n_322, n_323, n_402, n_404, n_405, n_407, n_408;
  wire n_421, n_422, n_423, n_424, n_425, n_428, n_429, n_431;
  wire n_460, n_464, n_519, n_526, n_529, n_540, n_542, n_581;
  wire n_582, n_584, n_585, n_587, n_591, n_594, n_596, n_609;
  wire n_610, n_632, n_635, n_641, n_643, n_649, n_656, n_657;
  wire n_659, n_661, n_662, n_663, n_664, n_665, n_666, n_667;
  wire n_668, n_672, n_676, n_680, n_681, n_682, n_683, n_684;
  wire n_685, n_688, n_689, n_690, n_691, n_692, n_693, n_695;
  wire n_697, n_698, n_702, n_707, n_708, n_709, n_710, n_711;
  wire n_712, n_713, n_714, n_716, n_717, n_718, n_719, n_723;
  wire n_726, n_728, n_733, n_734, n_735, n_736, n_738, n_743;
  wire n_745, n_747, n_760, n_768, n_770, n_771, n_772, n_773;
  wire n_776, n_777, n_778, n_779, n_780, n_781, n_782, n_783;
  wire n_786, n_787, n_789, n_790, n_791, n_792, n_799, n_800;
  wire n_801, n_802, n_804, n_805, n_806, n_818, n_820, n_821;
  wire n_822, n_823, n_824, n_825, n_826, n_828, n_829, n_830;
  wire n_831, n_833, n_834, n_835, n_836, n_854, n_856, n_877;
  wire n_878, n_879, n_880, n_900, n_902, n_906, n_907, n_908;
  wire n_909, n_910, n_911, n_912, n_928, n_929, n_930, n_931;
  wire n_956, n_958, n_963, n_964, n_965, n_988, n_989, n_990;
  wire n_996;
  DFFRHQX2 \count_reg[14] (.RN (n_158), .CK (clk), .D (n_587), .Q
       (count[14]));
  DFFRHQX4 \count_reg[7] (.RN (n_158), .CK (clk), .D (n_594), .Q
       (count[7]));
  DFFRHQX2 \count_reg[10] (.RN (n_158), .CK (clk), .D (n_610), .Q
       (count[10]));
  DFFRHQX4 \count_reg[5] (.RN (n_158), .CK (clk), .D (n_733), .Q
       (count[5]));
  DFFRHQX4 \count_reg[6] (.RN (n_158), .CK (clk), .D (n_581), .Q
       (count[6]));
  DFFRHQX2 \count_reg[13] (.RN (n_158), .CK (clk), .D (n_585), .Q
       (count[13]));
  DFFRHQX4 \count_reg[15] (.RN (n_158), .CK (clk), .D (n_804), .Q
       (count[15]));
  DFFRHQX8 \count_reg[12] (.RN (n_158), .CK (clk), .D (n_743), .Q
       (count[12]));
  DFFRHQX4 \count_reg[1] (.RN (n_158), .CK (clk), .D (n_582), .Q
       (count[1]));
  DFFRHQX4 \count_reg[8] (.RN (n_158), .CK (clk), .D (n_776), .Q
       (count[8]));
  DFFRHQX8 \count_reg[9] (.RN (n_158), .CK (clk), .D (n_906), .Q
       (count[9]));
  DFFRHQX4 \count_reg[0] (.RN (n_158), .CK (clk), .D (n_584), .Q
       (count[0]));
  DFFRHQX4 \count_reg[4] (.RN (n_158), .CK (clk), .D (n_786), .Q
       (count[4]));
  DFFRHQX8 \count_reg[2] (.RN (n_158), .CK (clk), .D (n_789), .Q
       (count[2]));
  DFFRHQX8 \count_reg[3] (.RN (n_158), .CK (clk), .D (n_591), .Q
       (count[3]));
  DFFRHQX4 CTR_OUT_reg(.RN (n_158), .CK (clk), .D (n_910), .Q
       (CTR_OUT));
  AOI2BB2X4 g4207__7482(.A0N (n_540), .A1N (n_911), .B0 (en_cnt), .B1
       (n_464), .Y (n_136));
  AOI2BB2X4 g4206__4733(.A0N (n_649), .A1N (n_132), .B0 (n_132), .B1
       (n_50), .Y (n_134));
  AOI2BB2X4 g4205__6161(.A0N (n_714), .A1N (n_464), .B0 (n_464), .B1
       (n_408), .Y (n_131));
  CLKAND2X6 g4224__8246(.A (n_736), .B (n_801), .Y (n_132));
  AOI2BB2X4 g4239__2883(.A0N (n_691), .A1N (n_728), .B0 (en_cnt), .B1
       (n_690), .Y (n_84));
  CLKAND2X6 g4292__7482(.A (n_649), .B (en_cnt), .Y (n_50));
  NAND2X2 g4289__9945(.A (en_cnt), .B (n_691), .Y (n_44));
  CLKAND2X3 g4243__2398(.A (n_831), .B (n_680), .Y (n_36));
  NOR2X2 g4258__1705(.A (count[6]), .B (count[2]), .Y (n_25));
  NOR2X2 g4268__5122(.A (count[15]), .B (count[3]), .Y (n_24));
  NOR2X2 g4263__7482(.A (count[7]), .B (count[8]), .Y (n_18));
  INVX1 g4305(.A (count[15]), .Y (n_9));
  INVXL g4329(.A (count[11]), .Y (n_123));
  INVX2 g4306(.A (count[14]), .Y (n_138));
  INVX1 g4341(.A (rst), .Y (n_158));
  CLKAND2X3 g4418(.A (count[9]), .B (n_431), .Y (n_289));
  AND3X6 g1(.A (n_695), .B (n_460), .C (n_690), .Y (n_316));
  AOI21X4 g4443(.A0 (n_635), .A1 (n_404), .B0 (n_322), .Y (n_323));
  AND2X1 g4444(.A (count[3]), .B (n_689), .Y (n_322));
  CLKAND2X6 g4294__4504(.A (en_cnt), .B (n_526), .Y (n_402));
  CLKAND2X6 g4233__4506(.A (n_632), .B (en_cnt), .Y (n_404));
  CLKAND2X3 g4290__4508(.A (n_123), .B (en_cnt), .Y (n_405));
  CLKAND2X6 g4278__4510(.A (n_138), .B (en_cnt), .Y (n_407));
  CLKAND2X6 g4293__4511(.A (n_714), .B (en_cnt), .Y (n_408));
  NAND2X2 g4271__4524(.A (load), .B (load_value[3]), .Y (n_421));
  NAND2X2 g4261__4525(.A (load), .B (load_value[5]), .Y (n_422));
  NOR2X8 g4287__4526(.A (n_707), .B (load), .Y (n_423));
  NAND2X2 g4280__4527(.A (load), .B (load_value[6]), .Y (n_424));
  NAND2X2 g4256__4528(.A (load), .B (load_value[12]), .Y (n_425));
  NAND2X2 g4285__4531(.A (load), .B (load_value[0]), .Y (n_428));
  NAND2X2 g4284__4532(.A (load), .B (load_value[15]), .Y (n_429));
  NOR2X8 g4296__4533(.A (en_cnt), .B (load), .Y (n_431));
  NOR2X4 g4270__4554(.A (count[3]), .B (count[2]), .Y (n_460));
  NOR2X6 g4220__4557(.A (n_542), .B (n_912), .Y (n_464));
  CLKAND2X2 g66(.A (n_856), .B (n_736), .Y (n_519));
  INVX6 fopt4(.A (load), .Y (n_526));
  BUFX2 fopt38(.A (count[14]), .Y (n_529));
  INVX1 fopt2(.A (n_540), .Y (n_542));
  BUFX6 fopt3(.A (n_712), .Y (n_540));
  OAI221X4 g4190__4628(.A0 (n_136), .A1 (n_770), .B0 (n_540), .B1
       (n_908), .C0 (n_424), .Y (n_581));
  OAI221X4 g4197__4629(.A0 (n_84), .A1 (n_770), .B0 (n_728), .B1
       (n_908), .C0 (n_657), .Y (n_582));
  OAI221X4 g4198__4631(.A0 (n_44), .A1 (n_770), .B0 (n_691), .B1
       (n_908), .C0 (n_428), .Y (n_584));
  OAI221X4 g4184__4632(.A0 (n_770), .A1 (n_134), .B0 (n_649), .B1
       (n_908), .C0 (n_683), .Y (n_585));
  OAI221X4 g4189__4634(.A0 (n_770), .A1 (n_931), .B0 (n_138), .B1
       (n_908), .C0 (n_681), .Y (n_587));
  OAI221X4 g4196__4637(.A0 (n_768), .A1 (n_323), .B0 (n_635), .B1
       (n_908), .C0 (n_421), .Y (n_591));
  OAI221X4 g4640(.A0 (n_714), .A1 (n_908), .B0 (n_768), .B1 (n_131),
       .C0 (n_661), .Y (n_594));
  NOR2BX2 g4643(.AN (count[5]), .B (n_316), .Y (n_596));
  OAI221X4 g32(.A0 (n_770), .A1 (n_836), .B0 (n_831), .B1 (n_908), .C0
       (n_609), .Y (n_610));
  INVX2 g33(.A (n_682), .Y (n_609));
  INVX3 fopt4661(.A (n_689), .Y (n_632));
  INVX2 fopt4663(.A (count[3]), .Y (n_635));
  INVX6 fopt4666(.A (n_643), .Y (n_641));
  BUFX6 fopt4668(.A (n_684), .Y (n_643));
  INVX3 fopt4673(.A (count[13]), .Y (n_649));
  CLKAND2X3 g4266__4676(.A (load_value[9]), .B (load), .Y (n_656));
  NAND2X2 g4260__4678(.A (load_value[1]), .B (load), .Y (n_657));
  CLKAND2X3 g4680(.A (load), .B (load_value[11]), .Y (n_659));
  NAND2X2 g4259__4681(.A (load_value[7]), .B (load), .Y (n_661));
  NAND2X2 g4255__4683(.A (load_value[2]), .B (load), .Y (n_662));
  NAND2X2 g4257__4684(.A (load_value[8]), .B (load), .Y (n_663));
  BUFX2 g4685(.A (n_693), .Y (n_664));
  NOR2X2 g125(.A (n_665), .B (n_666), .Y (n_667));
  NAND2X2 g134(.A (n_688), .B (n_708), .Y (n_665));
  NAND2X2 g135(.A (n_711), .B (n_709), .Y (n_666));
  NOR3X4 g123(.A (n_668), .B (n_738), .C (n_956), .Y (n_672));
  NAND2X4 g136(.A (n_691), .B (n_712), .Y (n_668));
  NOR2X6 g126(.A (n_713), .B (n_726), .Y (n_676));
  NOR2X6 g130(.A (count[8]), .B (count[9]), .Y (n_680));
  NAND2X2 g6(.A (load_value[14]), .B (load), .Y (n_681));
  CLKAND2X2 g7(.A (load), .B (load_value[10]), .Y (n_682));
  NAND2X2 g4686(.A (load_value[13]), .B (load), .Y (n_683));
  NAND3X8 g15(.A (n_685), .B (n_691), .C (n_688), .Y (n_689));
  INVX6 fopt21(.A (n_684), .Y (n_685));
  CLKBUFX4 fopt4687(.A (count[2]), .Y (n_684));
  CLKAND2X12 g16(.A (n_691), .B (n_688), .Y (n_690));
  INVX8 fopt4689(.A (count[4]), .Y (n_692));
  INVX8 fopt12(.A (count[5]), .Y (n_693));
  BUFX6 fopt4690(.A (n_692), .Y (n_695));
  CLKAND2X3 g118(.A (n_697), .B (n_25), .Y (n_698));
  NOR2X4 g4692(.A (count[12]), .B (count[9]), .Y (n_697));
  CLKAND2X3 g120(.A (n_18), .B (n_649), .Y (n_702));
  INVXL g4695(.A (count[9]), .Y (n_707));
  NAND2X8 g4696(.A (n_708), .B (n_709), .Y (n_710));
  INVX6 g10(.A (count[2]), .Y (n_708));
  INVX8 g4697(.A (count[3]), .Y (n_709));
  NAND2X8 g4698(.A (n_711), .B (n_712), .Y (n_713));
  INVX8 fopt4699(.A (count[7]), .Y (n_711));
  INVX8 g4700(.A (count[6]), .Y (n_712));
  CLKBUFX4 fopt4701(.A (n_711), .Y (n_714));
  NOR3X8 g29(.A (count[11]), .B (n_716), .C (n_717), .Y (n_718));
  BUFX6 fopt4702(.A (count[10]), .Y (n_716));
  OR2X6 g31(.A (count[12]), .B (count[13]), .Y (n_717));
  NOR2X6 g30(.A (count[11]), .B (count[10]), .Y (n_719));
  NOR2X8 g4705(.A (en_cnt), .B (load), .Y (n_723));
  NAND2X8 g4706(.A (n_691), .B (n_688), .Y (n_726));
  INVX12 fopt4707(.A (count[0]), .Y (n_691));
  INVX12 fopt4708(.A (count[1]), .Y (n_688));
  BUFX2 fopt5(.A (n_688), .Y (n_728));
  OAI221X4 g100(.A0 (n_768), .A1 (n_778), .B0 (n_664), .B1 (n_908), .C0
       (n_422), .Y (n_733));
  CLKAND2X12 g4711(.A (n_676), .B (n_735), .Y (n_736));
  NOR2X8 g28(.A (n_734), .B (n_710), .Y (n_735));
  NAND2X8 g4712(.A (n_692), .B (n_693), .Y (n_734));
  NAND2X4 g4713(.A (n_692), .B (n_693), .Y (n_738));
  OAI221X4 g4714(.A0 (n_768), .A1 (n_880), .B0 (n_747), .B1 (n_908),
       .C0 (n_425), .Y (n_743));
  INVX16 fopt4719(.A (en_cnt), .Y (n_745));
  INVX1 g8(.A (count[12]), .Y (n_747));
  OAI21X4 g4723(.A0 (n_929), .A1 (n_928), .B0 (n_138), .Y (n_760));
  INVX20 g11(.A (n_825), .Y (n_768));
  INVX20 g4724(.A (n_824), .Y (n_770));
  NAND2X2 g64(.A (count[15]), .B (n_772), .Y (n_773));
  NAND2BX4 g4725(.AN (n_929), .B (n_771), .Y (n_772));
  NOR2X4 g4726(.A (n_529), .B (n_928), .Y (n_771));
  OAI221X4 g4727(.A0 (n_963), .A1 (n_768), .B0 (n_856), .B1 (n_908),
       .C0 (n_663), .Y (n_776));
  AOI21X4 g22(.A0 (n_316), .A1 (n_777), .B0 (n_596), .Y (n_778));
  CLKAND2X6 g23(.A (n_664), .B (en_cnt), .Y (n_777));
  CLKAND2X6 g4729(.A (n_779), .B (n_719), .Y (n_780));
  NOR2X2 g4730(.A (count[1]), .B (count[14]), .Y (n_779));
  OAI21X4 g4731(.A0 (n_781), .A1 (n_405), .B0 (n_782), .Y (n_783));
  NAND2X4 g4732(.A (n_36), .B (n_736), .Y (n_781));
  NAND2BX2 g4733(.AN (count[11]), .B (n_781), .Y (n_782));
  OAI221X4 g4734(.A0 (n_768), .A1 (n_820), .B0 (n_695), .B1 (n_908),
       .C0 (n_958), .Y (n_786));
  OAI221X4 g4735(.A0 (n_770), .A1 (n_818), .B0 (n_641), .B1 (n_908),
       .C0 (n_662), .Y (n_789));
  NOR2X1 g4737(.A (n_690), .B (n_641), .Y (n_787));
  CLKAND2X3 g4738(.A (n_790), .B (n_24), .Y (n_791));
  NOR2X4 g4739(.A (count[4]), .B (count[5]), .Y (n_790));
  CLKAND2X6 g25(.A (n_790), .B (n_460), .Y (n_792));
  NOR3X6 g34(.A (count[12]), .B (n_799), .C (n_800), .Y (n_801));
  INVX2 g38(.A (n_680), .Y (n_799));
  INVX3 g37(.A (n_719), .Y (n_800));
  CLKAND2X2 g4745(.A (n_680), .B (n_719), .Y (n_802));
  OAI221X4 g43(.A0 (n_770), .A1 (n_773), .B0 (n_9), .B1 (n_908), .C0
       (n_429), .Y (n_804));
  OAI21X4 g4746(.A0 (n_768), .A1 (n_783), .B0 (n_805), .Y (n_806));
  NOR2X4 g4747(.A (n_965), .B (n_659), .Y (n_805));
  AOI21X4 g4753(.A0 (n_632), .A1 (en_cnt), .B0 (n_787), .Y (n_818));
  AOI21X4 g4755(.A0 (en_cnt), .A1 (n_316), .B0 (n_964), .Y (n_820));
  NOR2X8 g4756(.A (load), .B (n_823), .Y (n_824));
  NOR2X8 g4757(.A (n_821), .B (n_822), .Y (n_823));
  NAND2X8 g4758(.A (n_791), .B (n_698), .Y (n_821));
  NAND2X8 g4759(.A (n_780), .B (n_702), .Y (n_822));
  NOR2X8 g4760(.A (load), .B (n_823), .Y (n_825));
  NOR2X4 g116_dup(.A (n_821), .B (n_822), .Y (n_826));
  NOR2X4 g4762(.A (count[9]), .B (n_826), .Y (n_828));
  OAI21X4 g91(.A0 (n_830), .A1 (n_833), .B0 (n_835), .Y (n_836));
  INVX2 g93(.A (n_829), .Y (n_830));
  CLKAND2X3 g94(.A (n_672), .B (n_667), .Y (n_829));
  CLKAND2X6 g95(.A (n_831), .B (en_cnt), .Y (n_833));
  INVX3 fopt100(.A (count[10]), .Y (n_831));
  OR2X6 g92(.A (n_834), .B (n_829), .Y (n_835));
  INVXL fopt4763(.A (n_831), .Y (n_834));
  INVX2 fopt4770(.A (n_956), .Y (n_854));
  CLKINVX2 fopt4775(.A (count[8]), .Y (n_856));
  DFFRHQX4 \count_reg[11] (.RN (n_158), .CK (clk), .D (n_806), .Q
       (count[11]));
  OAI21X4 g59(.A0 (n_877), .A1 (n_878), .B0 (n_879), .Y (n_880));
  NAND2X8 g61(.A (n_736), .B (n_802), .Y (n_877));
  NOR2X4 g62(.A (count[12]), .B (n_745), .Y (n_878));
  NAND2BX2 g60(.AN (count[12]), .B (n_877), .Y (n_879));
  OAI21X4 g87(.A0 (n_900), .A1 (n_902), .B0 (n_990), .Y (n_906));
  INVX2 g4805(.A (n_402), .Y (n_900));
  NAND2X4 g89(.A (n_828), .B (n_996), .Y (n_902));
  OAI21X2 g4808(.A0 (n_907), .A1 (n_908), .B0 (n_909), .Y (n_910));
  INVX1 g4809(.A (CTR_OUT), .Y (n_907));
  INVX20 g4810(.A (n_723), .Y (n_908));
  NAND2X4 g4811(.A (n_826), .B (n_402), .Y (n_909));
  CLKAND2X6 g14(.A (n_690), .B (n_792), .Y (n_911));
  NAND2X6 g13(.A (n_690), .B (n_792), .Y (n_912));
  NAND2X8 g4821(.A (n_854), .B (n_718), .Y (n_928));
  INVX8 g4822(.A (n_736), .Y (n_929));
  OAI21X4 g4823(.A0 (n_930), .A1 (n_407), .B0 (n_760), .Y (n_931));
  OR2X6 g4824(.A (n_929), .B (n_928), .Y (n_930));
  OR2X6 g2(.A (count[8]), .B (count[9]), .Y (n_956));
  NAND2X2 g4850(.A (load), .B (load_value[4]), .Y (n_958));
  AOI2BB2X4 g4855(.A0N (n_856), .A1N (n_736), .B0 (en_cnt), .B1
       (n_519), .Y (n_963));
  AOI21X1 g4856(.A0 (n_460), .A1 (n_690), .B0 (n_695), .Y (n_964));
  NOR3X4 g4857(.A (load), .B (n_123), .C (en_cnt), .Y (n_965));
  NOR3X6 g4875(.A (n_656), .B (n_989), .C (n_289), .Y (n_990));
  NOR2X6 g4876(.A (n_996), .B (n_988), .Y (n_989));
  INVX8 g4877(.A (n_423), .Y (n_988));
  NOR2BX4 g4885(.AN (n_856), .B (n_929), .Y (n_996));
endmodule

