
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:39:16 IST (Feb 28 2026 10:09:16 UTC)

// Verification Directory fv/input_buffer_4x8 

module input_buffer_4x8(clk, rst, en_buf, DA, DB, DC, DD, DA_q, DB_q,
     DC_q, DD_q);
  input clk, rst, en_buf;
  input [7:0] DA, DB, DC, DD;
  output [7:0] DA_q, DB_q, DC_q, DD_q;
  wire clk, rst, en_buf;
  wire [7:0] DA, DB, DC, DD;
  wire [7:0] DA_q, DB_q, DC_q, DD_q;
  dff_W8 ff_DA(.clk (clk), .rst (rst), .en (en_buf), .d (DA), .q
       (DA_q));
  dff_W8 ff_DB(.clk (clk), .rst (rst), .en (en_buf), .d (DB), .q
       (DB_q));
  dff_W8 ff_DC(.clk (clk), .rst (rst), .en (en_buf), .d (DC), .q
       (DC_q));
  dff_W8 ff_DD(.clk (clk), .rst (rst), .en (en_buf), .d (DD), .q
       (DD_q));
endmodule

