
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:36:10 IST (Feb 28 2026 10:06:10 UTC)

// Verification Directory fv/mac_8x8_to_16 

module mac_8x8_to_16(clk, rst, en_mac, rst_mac, a, b, bias, sel_bias,
     acc_out);
  input clk, rst, en_mac, rst_mac, sel_bias;
  input [7:0] a, b;
  input [15:0] bias;
  output [15:0] acc_out;
  wire clk, rst, en_mac, rst_mac, sel_bias;
  wire [7:0] a, b;
  wire [15:0] bias;
  wire [15:0] acc_out;
  wire [15:0] base;
  wire [15:0] sum_sat;
  wire mul_17_32_n_0, mul_17_32_n_1, mul_17_32_n_3, mul_17_32_n_4,
       mul_17_32_n_5, mul_17_32_n_6, mul_17_32_n_9, mul_17_32_n_10;
  wire mul_17_32_n_11, mul_17_32_n_12, mul_17_32_n_13, mul_17_32_n_14,
       mul_17_32_n_15, mul_17_32_n_16, mul_17_32_n_17, mul_17_32_n_18;
  wire mul_17_32_n_19, mul_17_32_n_20, mul_17_32_n_21, mul_17_32_n_22,
       mul_17_32_n_23, mul_17_32_n_24, mul_17_32_n_25, mul_17_32_n_26;
  wire mul_17_32_n_27, mul_17_32_n_28, mul_17_32_n_29, mul_17_32_n_30,
       mul_17_32_n_31, mul_17_32_n_32, mul_17_32_n_33, mul_17_32_n_34;
  wire mul_17_32_n_35, mul_17_32_n_36, mul_17_32_n_37, mul_17_32_n_38,
       mul_17_32_n_39, mul_17_32_n_40, mul_17_32_n_41, mul_17_32_n_42;
  wire mul_17_32_n_43, mul_17_32_n_44, mul_17_32_n_45, mul_17_32_n_46,
       mul_17_32_n_47, mul_17_32_n_48, mul_17_32_n_49, mul_17_32_n_50;
  wire mul_17_32_n_51, mul_17_32_n_52, mul_17_32_n_53, mul_17_32_n_54,
       mul_17_32_n_55, mul_17_32_n_56, mul_17_32_n_57, mul_17_32_n_58;
  wire mul_17_32_n_59, mul_17_32_n_60, mul_17_32_n_61, mul_17_32_n_62,
       mul_17_32_n_63, mul_17_32_n_64, mul_17_32_n_65, mul_17_32_n_66;
  wire mul_17_32_n_67, mul_17_32_n_69, mul_17_32_n_70, mul_17_32_n_71,
       mul_17_32_n_72, mul_17_32_n_73, mul_17_32_n_74, mul_17_32_n_75;
  wire mul_17_32_n_76, mul_17_32_n_77, mul_17_32_n_78, mul_17_32_n_79,
       mul_17_32_n_80, mul_17_32_n_81, mul_17_32_n_82, mul_17_32_n_83;
  wire mul_17_32_n_84, mul_17_32_n_85, mul_17_32_n_86, mul_17_32_n_87,
       mul_17_32_n_88, mul_17_32_n_89, mul_17_32_n_90, mul_17_32_n_91;
  wire mul_17_32_n_92, mul_17_32_n_93, mul_17_32_n_94, mul_17_32_n_95,
       mul_17_32_n_96, mul_17_32_n_97, mul_17_32_n_98, mul_17_32_n_99;
  wire mul_17_32_n_100, mul_17_32_n_101, mul_17_32_n_102,
       mul_17_32_n_103, mul_17_32_n_104, mul_17_32_n_105,
       mul_17_32_n_106, mul_17_32_n_107;
  wire mul_17_32_n_108, mul_17_32_n_109, mul_17_32_n_110,
       mul_17_32_n_111, mul_17_32_n_112, mul_17_32_n_113,
       mul_17_32_n_114, mul_17_32_n_116;
  wire mul_17_32_n_117, mul_17_32_n_118, mul_17_32_n_120,
       mul_17_32_n_121, mul_17_32_n_122, mul_17_32_n_123,
       mul_17_32_n_124, mul_17_32_n_125;
  wire mul_17_32_n_126, mul_17_32_n_127, mul_17_32_n_128,
       mul_17_32_n_129, mul_17_32_n_130, mul_17_32_n_131,
       mul_17_32_n_132, mul_17_32_n_133;
  wire mul_17_32_n_134, mul_17_32_n_135, mul_17_32_n_136,
       mul_17_32_n_138, mul_17_32_n_139, mul_17_32_n_140,
       mul_17_32_n_141, mul_17_32_n_142;
  wire mul_17_32_n_143, mul_17_32_n_144, mul_17_32_n_146,
       mul_17_32_n_147, mul_17_32_n_148, mul_17_32_n_149,
       mul_17_32_n_150, mul_17_32_n_152;
  wire mul_17_32_n_154, mul_17_32_n_156, mul_17_32_n_158,
       mul_17_32_n_160, mul_17_32_n_162, mul_17_32_n_164,
       mul_17_32_n_166, mul_17_32_n_168;
  wire mul_17_32_n_170, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_51, n_52, n_53, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_210;
  wire n_216, n_218, n_221, n_224, n_231, n_234, n_235, n_236;
  wire n_237, n_240, n_241, n_242, n_243, n_259, n_260, n_261;
  wire n_266, n_267, n_268, n_270, n_271, n_273, n_274, n_276;
  wire n_277, n_279, n_280, n_282, n_283, n_288, n_289, n_291;
  wire n_292, n_294, n_295, n_297, n_298, n_300, n_301, n_303;
  wire n_304, n_306, n_307, n_309, n_310, n_312, n_313, n_315;
  wire n_316, n_365, n_366;
  sat_add16 u_add(.a ({n_136, n_134, n_132, n_130, n_128, n_126, n_124,
       n_122, n_120, n_118, n_116, n_114, n_112, n_110, n_108, n_106}),
       .b (base), .y (sum_sat));
  MX2XL g1382__2398(.A (n_298), .B (bias[13]), .S0 (sel_bias), .Y
       (base[13]));
  MX2XL g1383__5107(.A (n_301), .B (bias[9]), .S0 (sel_bias), .Y
       (base[9]));
  MX2X2 g1384__6260(.A (n_366), .B (bias[8]), .S0 (sel_bias), .Y
       (base[8]));
  MX2XL g1385__4319(.A (n_274), .B (bias[11]), .S0 (sel_bias), .Y
       (base[11]));
  MX2XL g1386__8428(.A (n_271), .B (bias[3]), .S0 (sel_bias), .Y
       (base[3]));
  MX2XL g1387__5526(.A (n_310), .B (bias[6]), .S0 (sel_bias), .Y
       (base[6]));
  MX2XL g1388__6783(.A (n_295), .B (bias[10]), .S0 (sel_bias), .Y
       (base[10]));
  MX2XL g1389__3680(.A (n_280), .B (bias[5]), .S0 (sel_bias), .Y
       (base[5]));
  MX2XL g1390__1617(.A (n_292), .B (bias[14]), .S0 (sel_bias), .Y
       (base[14]));
  MX2XL g1391__2802(.A (n_283), .B (bias[4]), .S0 (sel_bias), .Y
       (base[4]));
  MX2XL g1392__1705(.A (n_304), .B (bias[1]), .S0 (sel_bias), .Y
       (base[1]));
  MX2XL g1393__5122(.A (n_307), .B (bias[15]), .S0 (sel_bias), .Y
       (base[15]));
  MX2XL g1394__8246(.A (n_289), .B (bias[2]), .S0 (sel_bias), .Y
       (base[2]));
  MX2XL g1395__7098(.A (n_277), .B (bias[12]), .S0 (sel_bias), .Y
       (base[12]));
  MX2XL g1396__6131(.A (n_268), .B (bias[7]), .S0 (sel_bias), .Y
       (base[7]));
  MX2XL g1397__1881(.A (n_313), .B (bias[0]), .S0 (sel_bias), .Y
       (base[0]));
  DFFHQX4 \acc_out_reg[8] (.CK (clk), .D (n_266), .Q (acc_out[8]));
  DFFHQX1 \acc_out_reg[5] (.CK (clk), .D (n_38), .Q (acc_out[5]));
  DFFHQX1 \acc_out_reg[6] (.CK (clk), .D (n_52), .Q (acc_out[6]));
  DFFHQX1 \acc_out_reg[7] (.CK (clk), .D (n_51), .Q (acc_out[7]));
  DFFHQX1 \acc_out_reg[0] (.CK (clk), .D (n_49), .Q (acc_out[0]));
  DFFHQX1 \acc_out_reg[9] (.CK (clk), .D (n_53), .Q (acc_out[9]));
  DFFHQX1 \acc_out_reg[10] (.CK (clk), .D (n_48), .Q (acc_out[10]));
  DFFHQX1 \acc_out_reg[11] (.CK (clk), .D (n_46), .Q (acc_out[11]));
  DFFHQX1 \acc_out_reg[14] (.CK (clk), .D (n_43), .Q (acc_out[14]));
  DFFHQX1 \acc_out_reg[1] (.CK (clk), .D (n_47), .Q (acc_out[1]));
  DFFHQX1 \acc_out_reg[2] (.CK (clk), .D (n_45), .Q (acc_out[2]));
  DFFHQX1 \acc_out_reg[13] (.CK (clk), .D (n_44), .Q (acc_out[13]));
  DFFHQX1 \acc_out_reg[12] (.CK (clk), .D (n_41), .Q (acc_out[12]));
  DFFHQX1 \acc_out_reg[15] (.CK (clk), .D (n_42), .Q (acc_out[15]));
  DFFHQX1 \acc_out_reg[3] (.CK (clk), .D (n_40), .Q (acc_out[3]));
  DFFHQX1 \acc_out_reg[4] (.CK (clk), .D (n_39), .Q (acc_out[4]));
  OAI22X4 g1976__5115(.A0 (n_300), .A1 (n_216), .B0 (n_30), .B1
       (n_210), .Y (n_53));
  OAI22X4 g1977__7482(.A0 (n_309), .A1 (n_237), .B0 (n_29), .B1
       (n_210), .Y (n_52));
  OAI22X4 g1978__4733(.A0 (n_267), .A1 (n_237), .B0 (n_32), .B1
       (n_210), .Y (n_51));
  OAI22X4 g1980__9315(.A0 (n_312), .A1 (n_237), .B0 (n_15), .B1
       (n_210), .Y (n_49));
  OAI22X4 g1981__9945(.A0 (n_294), .A1 (n_216), .B0 (n_25), .B1
       (n_210), .Y (n_48));
  OAI22X4 g1982__2883(.A0 (n_303), .A1 (n_237), .B0 (n_31), .B1
       (n_210), .Y (n_47));
  OAI22X4 g1983__2346(.A0 (n_273), .A1 (n_216), .B0 (n_13), .B1
       (n_210), .Y (n_46));
  OAI22X4 g1984__1666(.A0 (n_288), .A1 (n_237), .B0 (n_12), .B1
       (n_210), .Y (n_45));
  OAI22X4 g1985__7410(.A0 (n_297), .A1 (n_216), .B0 (n_26), .B1
       (n_210), .Y (n_44));
  OAI22X4 g1986__6417(.A0 (n_291), .A1 (n_237), .B0 (n_28), .B1
       (n_210), .Y (n_43));
  OAI22X4 g1987__5477(.A0 (n_306), .A1 (n_237), .B0 (n_14), .B1
       (n_210), .Y (n_42));
  OAI22X4 g1988__2398(.A0 (n_276), .A1 (n_237), .B0 (n_27), .B1
       (n_210), .Y (n_41));
  OAI22X4 g1989__5107(.A0 (n_270), .A1 (n_216), .B0 (n_10), .B1
       (n_210), .Y (n_40));
  OAI22X4 g1990__6260(.A0 (n_282), .A1 (n_216), .B0 (n_9), .B1 (n_210),
       .Y (n_39));
  OAI22X4 g1991__4319(.A0 (n_279), .A1 (n_216), .B0 (n_11), .B1
       (n_210), .Y (n_38));
  INVX1 g1997(.A (sum_sat[7]), .Y (n_32));
  INVX1 g1998(.A (sum_sat[1]), .Y (n_31));
  INVX1 g1999(.A (sum_sat[9]), .Y (n_30));
  INVX1 g2000(.A (sum_sat[6]), .Y (n_29));
  INVX1 g2001(.A (sum_sat[14]), .Y (n_28));
  INVX1 g2002(.A (sum_sat[12]), .Y (n_27));
  INVX1 g2003(.A (sum_sat[13]), .Y (n_26));
  INVX1 g2004(.A (sum_sat[10]), .Y (n_25));
  INVX1 g2014(.A (sum_sat[0]), .Y (n_15));
  INVX1 g2015(.A (sum_sat[15]), .Y (n_14));
  INVX1 g2016(.A (sum_sat[11]), .Y (n_13));
  INVX1 g2017(.A (sum_sat[2]), .Y (n_12));
  INVX1 g2018(.A (sum_sat[5]), .Y (n_11));
  INVX1 g2019(.A (sum_sat[3]), .Y (n_10));
  INVX1 g2020(.A (sum_sat[4]), .Y (n_9));
  BUFX2 g2030(.A (n_137), .Y (n_136));
  BUFX2 g2031(.A (n_135), .Y (n_134));
  BUFX2 g2032(.A (n_133), .Y (n_132));
  BUFX2 g2033(.A (n_131), .Y (n_130));
  BUFX2 g2034(.A (n_129), .Y (n_128));
  BUFX2 g2035(.A (n_127), .Y (n_126));
  BUFX2 g2036(.A (n_125), .Y (n_124));
  BUFX2 g2037(.A (n_123), .Y (n_122));
  BUFX2 g2038(.A (n_121), .Y (n_120));
  BUFX2 g2039(.A (n_119), .Y (n_118));
  BUFX2 g2040(.A (n_117), .Y (n_116));
  BUFX2 g2041(.A (n_115), .Y (n_114));
  BUFX2 g2042(.A (n_113), .Y (n_112));
  BUFX2 g2043(.A (n_111), .Y (n_110));
  BUFX2 g2044(.A (n_109), .Y (n_108));
  BUFX3 g2045(.A (n_107), .Y (n_106));
  INVX1 mul_17_32_g1456(.A (mul_17_32_n_170), .Y (n_135));
  ADDFXL mul_17_32_g1457__3680(.A (mul_17_32_n_97), .B
       (mul_17_32_n_83), .CI (mul_17_32_n_168), .CO (n_137), .S
       (mul_17_32_n_170));
  INVX1 mul_17_32_g1458(.A (mul_17_32_n_166), .Y (mul_17_32_n_168));
  ADDFXL mul_17_32_g1459__1617(.A (mul_17_32_n_83), .B
       (mul_17_32_n_116), .CI (mul_17_32_n_164), .CO (mul_17_32_n_166),
       .S (n_133));
  ADDFXL mul_17_32_g1460__2802(.A (mul_17_32_n_117), .B
       (mul_17_32_n_138), .CI (mul_17_32_n_162), .CO (mul_17_32_n_164),
       .S (n_131));
  ADDFXL mul_17_32_g1461__1705(.A (mul_17_32_n_139), .B
       (mul_17_32_n_140), .CI (mul_17_32_n_160), .CO (mul_17_32_n_162),
       .S (n_129));
  ADDFXL mul_17_32_g1462__5122(.A (mul_17_32_n_148), .B
       (mul_17_32_n_141), .CI (mul_17_32_n_158), .CO (mul_17_32_n_160),
       .S (n_127));
  ADDFXL mul_17_32_g1463__8246(.A (mul_17_32_n_146), .B
       (mul_17_32_n_149), .CI (mul_17_32_n_156), .CO (mul_17_32_n_158),
       .S (n_125));
  ADDFXL mul_17_32_g1464__7098(.A (mul_17_32_n_142), .B
       (mul_17_32_n_147), .CI (mul_17_32_n_154), .CO (mul_17_32_n_156),
       .S (n_123));
  ADDFXL mul_17_32_g1465__6131(.A (mul_17_32_n_134), .B
       (mul_17_32_n_143), .CI (mul_17_32_n_152), .CO (mul_17_32_n_154),
       .S (n_121));
  ADDFXL mul_17_32_g1466__1881(.A (mul_17_32_n_120), .B
       (mul_17_32_n_135), .CI (mul_17_32_n_150), .CO (mul_17_32_n_152),
       .S (n_119));
  ADDFXL mul_17_32_g1467__5115(.A (mul_17_32_n_124), .B
       (mul_17_32_n_121), .CI (mul_17_32_n_144), .CO (mul_17_32_n_150),
       .S (n_117));
  ADDFXL mul_17_32_g1468__7482(.A (mul_17_32_n_110), .B
       (mul_17_32_n_132), .CI (mul_17_32_n_127), .CO (mul_17_32_n_148),
       .S (mul_17_32_n_149));
  ADDFXL mul_17_32_g1469__4733(.A (mul_17_32_n_114), .B
       (mul_17_32_n_130), .CI (mul_17_32_n_133), .CO (mul_17_32_n_146),
       .S (mul_17_32_n_147));
  ADDFXL mul_17_32_g1470__6161(.A (mul_17_32_n_107), .B
       (mul_17_32_n_125), .CI (mul_17_32_n_136), .CO (mul_17_32_n_144),
       .S (n_115));
  ADDFXL mul_17_32_g1471__9315(.A (mul_17_32_n_113), .B
       (mul_17_32_n_128), .CI (mul_17_32_n_131), .CO (mul_17_32_n_142),
       .S (mul_17_32_n_143));
  ADDFXL mul_17_32_g1472__9945(.A (mul_17_32_n_86), .B
       (mul_17_32_n_126), .CI (mul_17_32_n_123), .CO (mul_17_32_n_140),
       .S (mul_17_32_n_141));
  ADDFXL mul_17_32_g1473__2883(.A (mul_17_32_n_93), .B
       (mul_17_32_n_85), .CI (mul_17_32_n_122), .CO (mul_17_32_n_138),
       .S (mul_17_32_n_139));
  ADDFXL mul_17_32_g1474__2346(.A (mul_17_32_n_94), .B
       (mul_17_32_n_111), .CI (mul_17_32_n_118), .CO (mul_17_32_n_136),
       .S (n_113));
  ADDFXL mul_17_32_g1475__1666(.A (mul_17_32_n_91), .B
       (mul_17_32_n_109), .CI (mul_17_32_n_129), .CO (mul_17_32_n_134),
       .S (mul_17_32_n_135));
  ADDFXL mul_17_32_g1476__7410(.A (mul_17_32_n_100), .B
       (mul_17_32_n_76), .CI (mul_17_32_n_108), .CO (mul_17_32_n_132),
       .S (mul_17_32_n_133));
  ADDFXL mul_17_32_g1477__6417(.A (mul_17_32_n_75), .B
       (mul_17_32_n_73), .CI (mul_17_32_n_81), .CO (mul_17_32_n_130),
       .S (mul_17_32_n_131));
  ADDFXL mul_17_32_g1478__5477(.A (mul_17_32_n_66), .B
       (mul_17_32_n_95), .CI (mul_17_32_n_99), .CO (mul_17_32_n_128),
       .S (mul_17_32_n_129));
  ADDFXL mul_17_32_g1479__2398(.A (mul_17_32_n_72), .B
       (mul_17_32_n_92), .CI (mul_17_32_n_87), .CO (mul_17_32_n_126),
       .S (mul_17_32_n_127));
  ADDFXL mul_17_32_g1480__5107(.A (mul_17_32_n_64), .B
       (mul_17_32_n_101), .CI (mul_17_32_n_74), .CO (mul_17_32_n_124),
       .S (mul_17_32_n_125));
  ADDFXL mul_17_32_g1481__6260(.A (mul_17_32_n_77), .B
       (mul_17_32_n_98), .CI (mul_17_32_n_80), .CO (mul_17_32_n_122),
       .S (mul_17_32_n_123));
  ADDFXL mul_17_32_g1482__4319(.A (mul_17_32_n_79), .B
       (mul_17_32_n_78), .CI (mul_17_32_n_112), .CO (mul_17_32_n_120),
       .S (mul_17_32_n_121));
  ADDFXL mul_17_32_g1483__8428(.A (mul_17_32_n_65), .B
       (mul_17_32_n_96), .CI (mul_17_32_n_106), .CO (mul_17_32_n_118),
       .S (n_111));
  ADDFXL mul_17_32_g1484__5526(.A (mul_17_32_n_90), .B
       (mul_17_32_n_82), .CI (mul_17_32_n_84), .CO (mul_17_32_n_116),
       .S (mul_17_32_n_117));
  AOI21XL mul_17_32_g1485__6783(.A0 (mul_17_32_n_47), .A1
       (mul_17_32_n_105), .B0 (mul_17_32_n_106), .Y (n_109));
  OAI2BB1X1 mul_17_32_g1486__3680(.A0N (mul_17_32_n_88), .A1N
       (mul_17_32_n_89), .B0 (mul_17_32_n_110), .Y (mul_17_32_n_114));
  CLKXOR2X1 mul_17_32_g1487__1617(.A (mul_17_32_n_71), .B
       (mul_17_32_n_104), .Y (mul_17_32_n_113));
  CLKXOR2X1 mul_17_32_g1488__2802(.A (mul_17_32_n_70), .B
       (mul_17_32_n_102), .Y (mul_17_32_n_112));
  CLKXOR2X1 mul_17_32_g1489__1705(.A (mul_17_32_n_69), .B
       (mul_17_32_n_103), .Y (mul_17_32_n_111));
  OR2X1 mul_17_32_g1490__5122(.A (mul_17_32_n_88), .B (mul_17_32_n_89),
       .Y (mul_17_32_n_110));
  NOR2XL mul_17_32_g1491__8246(.A (mul_17_32_n_70), .B
       (mul_17_32_n_102), .Y (mul_17_32_n_109));
  NOR2XL mul_17_32_g1492__7098(.A (mul_17_32_n_71), .B
       (mul_17_32_n_104), .Y (mul_17_32_n_108));
  NOR2XL mul_17_32_g1493__6131(.A (mul_17_32_n_69), .B
       (mul_17_32_n_103), .Y (mul_17_32_n_107));
  NOR2XL mul_17_32_g1494__1881(.A (mul_17_32_n_47), .B
       (mul_17_32_n_105), .Y (mul_17_32_n_106));
  AOI22XL mul_17_32_g1495__5115(.A0 (mul_17_32_n_0), .A1 (n_316), .B0
       (b[0]), .B1 (mul_17_32_n_26), .Y (mul_17_32_n_105));
  AOI22XL mul_17_32_g1496__7482(.A0 (mul_17_32_n_29), .A1 (n_316), .B0
       (b[0]), .B1 (mul_17_32_n_21), .Y (mul_17_32_n_104));
  OAI22XL mul_17_32_g1497__4733(.A0 (mul_17_32_n_43), .A1
       (mul_17_32_n_67), .B0 (mul_17_32_n_1), .B1 (mul_17_32_n_48), .Y
       (mul_17_32_n_101));
  AOI22XL mul_17_32_g1498__6161(.A0 (mul_17_32_n_46), .A1 (n_316), .B0
       (b[0]), .B1 (mul_17_32_n_44), .Y (mul_17_32_n_103));
  OAI21XL mul_17_32_g1499__9315(.A0 (b[0]), .A1 (n_316), .B0
       (mul_17_32_n_21), .Y (mul_17_32_n_100));
  OAI22XL mul_17_32_g1500__9945(.A0 (mul_17_32_n_56), .A1
       (mul_17_32_n_60), .B0 (mul_17_32_n_20), .B1 (mul_17_32_n_39), .Y
       (mul_17_32_n_99));
  AOI22XL mul_17_32_g1501__2883(.A0 (mul_17_32_n_49), .A1 (n_316), .B0
       (b[0]), .B1 (mul_17_32_n_55), .Y (mul_17_32_n_102));
  OAI21XL mul_17_32_g1502__2346(.A0 (mul_17_32_n_38), .A1
       (mul_17_32_n_59), .B0 (mul_17_32_n_52), .Y (mul_17_32_n_98));
  AOI21XL mul_17_32_g1503__1666(.A0 (mul_17_32_n_40), .A1
       (mul_17_32_n_61), .B0 (mul_17_32_n_13), .Y (mul_17_32_n_97));
  OAI22XL mul_17_32_g1504__7410(.A0 (mul_17_32_n_25), .A1
       (mul_17_32_n_67), .B0 (mul_17_32_n_1), .B1 (mul_17_32_n_45), .Y
       (mul_17_32_n_96));
  OAI22XL mul_17_32_g1505__6417(.A0 (mul_17_32_n_54), .A1
       (mul_17_32_n_67), .B0 (mul_17_32_n_1), .B1 (mul_17_32_n_28), .Y
       (mul_17_32_n_95));
  OAI22XL mul_17_32_g1506__5477(.A0 (mul_17_32_n_33), .A1
       (mul_17_32_n_60), .B0 (mul_17_32_n_53), .B1 (mul_17_32_n_39), .Y
       (mul_17_32_n_94));
  OAI22XL mul_17_32_g1507__2398(.A0 (mul_17_32_n_30), .A1
       (mul_17_32_n_63), .B0 (mul_17_32_n_23), .B1 (mul_17_32_n_12), .Y
       (mul_17_32_n_93));
  OAI22XL mul_17_32_g1508__5107(.A0 (mul_17_32_n_57), .A1
       (mul_17_32_n_60), .B0 (mul_17_32_n_51), .B1 (mul_17_32_n_39), .Y
       (mul_17_32_n_92));
  OAI22XL mul_17_32_g1509__6260(.A0 (mul_17_32_n_27), .A1
       (mul_17_32_n_63), .B0 (mul_17_32_n_58), .B1 (mul_17_32_n_12), .Y
       (mul_17_32_n_91));
  OAI21XL mul_17_32_g1510__4319(.A0 (mul_17_32_n_11), .A1
       (mul_17_32_n_62), .B0 (mul_17_32_n_24), .Y (mul_17_32_n_90));
  INVX1 mul_17_32_g1511(.A (mul_17_32_n_86), .Y (mul_17_32_n_87));
  INVX1 mul_17_32_g1512(.A (mul_17_32_n_84), .Y (mul_17_32_n_85));
  OAI22XL mul_17_32_g1513__8428(.A0 (mul_17_32_n_50), .A1
       (mul_17_32_n_60), .B0 (mul_17_32_n_57), .B1 (mul_17_32_n_39), .Y
       (mul_17_32_n_89));
  OAI22XL mul_17_32_g1514__5526(.A0 (mul_17_32_n_16), .A1
       (mul_17_32_n_61), .B0 (mul_17_32_n_18), .B1 (mul_17_32_n_40), .Y
       (mul_17_32_n_88));
  OAI22XL mul_17_32_g1515__6783(.A0 (mul_17_32_n_17), .A1
       (mul_17_32_n_61), .B0 (mul_17_32_n_15), .B1 (mul_17_32_n_40), .Y
       (mul_17_32_n_82));
  OAI22XL mul_17_32_g1516__3680(.A0 (mul_17_32_n_58), .A1
       (mul_17_32_n_63), .B0 (mul_17_32_n_41), .B1 (mul_17_32_n_12), .Y
       (mul_17_32_n_81));
  OAI22XL mul_17_32_g1517__1617(.A0 (mul_17_32_n_14), .A1
       (mul_17_32_n_61), .B0 (mul_17_32_n_19), .B1 (mul_17_32_n_40), .Y
       (mul_17_32_n_80));
  OAI22XL mul_17_32_g1518__2802(.A0 (mul_17_32_n_10), .A1
       (mul_17_32_n_63), .B0 (mul_17_32_n_27), .B1 (mul_17_32_n_12), .Y
       (mul_17_32_n_79));
  OAI22XL mul_17_32_g1519__1705(.A0 (mul_17_32_n_42), .A1
       (mul_17_32_n_60), .B0 (mul_17_32_n_56), .B1 (mul_17_32_n_39), .Y
       (mul_17_32_n_78));
  OAI22XL mul_17_32_g1520__5122(.A0 (mul_17_32_n_31), .A1
       (mul_17_32_n_63), .B0 (mul_17_32_n_30), .B1 (mul_17_32_n_12), .Y
       (mul_17_32_n_77));
  OAI22XL mul_17_32_g1521__8246(.A0 (mul_17_32_n_41), .A1
       (mul_17_32_n_63), .B0 (mul_17_32_n_22), .B1 (mul_17_32_n_12), .Y
       (mul_17_32_n_76));
  OAI22XL mul_17_32_g1522__7098(.A0 (mul_17_32_n_6), .A1
       (mul_17_32_n_61), .B0 (mul_17_32_n_16), .B1 (mul_17_32_n_40), .Y
       (mul_17_32_n_75));
  OAI22XL mul_17_32_g1523__6131(.A0 (mul_17_32_n_53), .A1
       (mul_17_32_n_60), .B0 (mul_17_32_n_42), .B1 (mul_17_32_n_39), .Y
       (mul_17_32_n_74));
  OAI22XL mul_17_32_g1524__1881(.A0 (mul_17_32_n_20), .A1
       (mul_17_32_n_60), .B0 (mul_17_32_n_50), .B1 (mul_17_32_n_39), .Y
       (mul_17_32_n_73));
  OAI22XL mul_17_32_g1525__5115(.A0 (mul_17_32_n_18), .A1
       (mul_17_32_n_61), .B0 (mul_17_32_n_14), .B1 (mul_17_32_n_40), .Y
       (mul_17_32_n_72));
  OAI22XL mul_17_32_g1526__7482(.A0 (mul_17_32_n_22), .A1
       (mul_17_32_n_63), .B0 (mul_17_32_n_31), .B1 (mul_17_32_n_12), .Y
       (mul_17_32_n_86));
  OAI22XL mul_17_32_g1527__4733(.A0 (mul_17_32_n_19), .A1
       (mul_17_32_n_61), .B0 (mul_17_32_n_17), .B1 (mul_17_32_n_40), .Y
       (mul_17_32_n_84));
  OA22X1 mul_17_32_g1528__6161(.A0 (mul_17_32_n_15), .A1
       (mul_17_32_n_61), .B0 (mul_17_32_n_13), .B1 (mul_17_32_n_40), .Y
       (mul_17_32_n_83));
  OAI21XL mul_17_32_g1529__9315(.A0 (mul_17_32_n_3), .A1
       (mul_17_32_n_35), .B0 (b[7]), .Y (mul_17_32_n_71));
  OAI21XL mul_17_32_g1530__9945(.A0 (mul_17_32_n_5), .A1
       (mul_17_32_n_37), .B0 (b[5]), .Y (mul_17_32_n_70));
  OAI21XL mul_17_32_g1531__2883(.A0 (mul_17_32_n_4), .A1
       (mul_17_32_n_36), .B0 (b[3]), .Y (mul_17_32_n_69));
  INVX1 mul_17_32_g1532(.A (n_316), .Y (mul_17_32_n_67));
  NOR2XL mul_17_32_g1534__1666(.A (mul_17_32_n_0), .B (mul_17_32_n_40),
       .Y (mul_17_32_n_66));
  NOR2XL mul_17_32_g1535__7410(.A (mul_17_32_n_0), .B (mul_17_32_n_39),
       .Y (mul_17_32_n_65));
  NOR2XL mul_17_32_g1536__6417(.A (mul_17_32_n_0), .B (mul_17_32_n_12),
       .Y (mul_17_32_n_64));
  INVX1 mul_17_32_g1537(.A (mul_17_32_n_63), .Y (mul_17_32_n_62));
  OR2X1 mul_17_32_g1538__5477(.A (mul_17_32_n_34), .B (mul_17_32_n_11),
       .Y (mul_17_32_n_63));
  NAND2X1 mul_17_32_g1539__2398(.A (mul_17_32_n_9), .B
       (mul_17_32_n_40), .Y (mul_17_32_n_61));
  INVX1 mul_17_32_g1540(.A (mul_17_32_n_60), .Y (mul_17_32_n_59));
  OR2X1 mul_17_32_g1541__5107(.A (mul_17_32_n_32), .B (mul_17_32_n_38),
       .Y (mul_17_32_n_60));
  INVX1 mul_17_32_g1542(.A (mul_17_32_n_54), .Y (mul_17_32_n_55));
  INVX1 mul_17_32_g1543(.A (mul_17_32_n_51), .Y (mul_17_32_n_52));
  INVX1 mul_17_32_g1544(.A (mul_17_32_n_48), .Y (mul_17_32_n_49));
  INVX1 mul_17_32_g1545(.A (mul_17_32_n_45), .Y (mul_17_32_n_46));
  INVX1 mul_17_32_g1546(.A (mul_17_32_n_43), .Y (mul_17_32_n_44));
  INVX1 mul_17_32_g1547(.A (mul_17_32_n_39), .Y (mul_17_32_n_38));
  AOI21XL mul_17_32_g1548__6260(.A0 (a[0]), .A1 (b[4]), .B0 (b[3]), .Y
       (mul_17_32_n_37));
  AOI21XL mul_17_32_g1549__4319(.A0 (a[0]), .A1 (b[2]), .B0 (b[1]), .Y
       (mul_17_32_n_36));
  AOI21XL mul_17_32_g1550__8428(.A0 (a[0]), .A1 (b[6]), .B0 (b[5]), .Y
       (mul_17_32_n_35));
  XNOR2X1 mul_17_32_g1551__5526(.A (b[4]), .B (b[5]), .Y
       (mul_17_32_n_34));
  MXI2XL mul_17_32_g1552__6783(.A (a[0]), .B (mul_17_32_n_0), .S0
       (b[3]), .Y (mul_17_32_n_33));
  XNOR2X1 mul_17_32_g1553__3680(.A (b[2]), .B (b[3]), .Y
       (mul_17_32_n_32));
  XNOR2X1 mul_17_32_g1554__1617(.A (b[5]), .B (a[2]), .Y
       (mul_17_32_n_58));
  XNOR2X1 mul_17_32_g1555__2802(.A (b[3]), .B (a[6]), .Y
       (mul_17_32_n_57));
  XNOR2X1 mul_17_32_g1556__1705(.A (b[3]), .B (a[3]), .Y
       (mul_17_32_n_56));
  XNOR2X1 mul_17_32_g1557__5122(.A (b[1]), .B (a[5]), .Y
       (mul_17_32_n_54));
  XNOR2X1 mul_17_32_g1558__8246(.A (b[3]), .B (a[1]), .Y
       (mul_17_32_n_53));
  XNOR2X1 mul_17_32_g1559__7098(.A (b[3]), .B (a[7]), .Y
       (mul_17_32_n_51));
  XNOR2X1 mul_17_32_g1560__6131(.A (b[3]), .B (a[5]), .Y
       (mul_17_32_n_50));
  XNOR2X1 mul_17_32_g1561__1881(.A (b[1]), .B (a[4]), .Y
       (mul_17_32_n_48));
  NAND2BX1 mul_17_32_g1562__5115(.AN (n_107), .B (b[1]), .Y
       (mul_17_32_n_47));
  XNOR2X1 mul_17_32_g1563__7482(.A (b[1]), .B (a[2]), .Y
       (mul_17_32_n_45));
  XNOR2X1 mul_17_32_g1564__4733(.A (b[1]), .B (a[3]), .Y
       (mul_17_32_n_43));
  XNOR2X1 mul_17_32_g1565__6161(.A (b[3]), .B (a[2]), .Y
       (mul_17_32_n_42));
  XNOR2X1 mul_17_32_g1566__9315(.A (b[5]), .B (a[3]), .Y
       (mul_17_32_n_41));
  XNOR2X1 mul_17_32_g1567__9945(.A (b[5]), .B (b[6]), .Y
       (mul_17_32_n_40));
  XNOR2X1 mul_17_32_g1568__2883(.A (b[1]), .B (b[2]), .Y
       (mul_17_32_n_39));
  INVX1 mul_17_32_g1569(.A (mul_17_32_n_28), .Y (mul_17_32_n_29));
  INVX1 mul_17_32_g1570(.A (mul_17_32_n_25), .Y (mul_17_32_n_26));
  INVX1 mul_17_32_g1571(.A (mul_17_32_n_23), .Y (mul_17_32_n_24));
  INVX1 mul_17_32_g1572(.A (mul_17_32_n_12), .Y (mul_17_32_n_11));
  MXI2XL mul_17_32_g1573__2346(.A (a[0]), .B (mul_17_32_n_0), .S0
       (b[5]), .Y (mul_17_32_n_10));
  CLKXOR2X1 mul_17_32_g1574__1666(.A (b[6]), .B (b[7]), .Y
       (mul_17_32_n_9));
  MXI2XL mul_17_32_g1577__7410(.A (a[0]), .B (mul_17_32_n_0), .S0
       (b[7]), .Y (mul_17_32_n_6));
  XNOR2X1 mul_17_32_g1578__6417(.A (b[5]), .B (a[5]), .Y
       (mul_17_32_n_31));
  XNOR2X1 mul_17_32_g1579__5477(.A (b[5]), .B (a[6]), .Y
       (mul_17_32_n_30));
  XNOR2X1 mul_17_32_g1580__2398(.A (b[1]), .B (a[6]), .Y
       (mul_17_32_n_28));
  XNOR2X1 mul_17_32_g1581__5107(.A (b[5]), .B (a[1]), .Y
       (mul_17_32_n_27));
  XNOR2X1 mul_17_32_g1582__6260(.A (b[1]), .B (a[1]), .Y
       (mul_17_32_n_25));
  XNOR2X1 mul_17_32_g1583__4319(.A (b[5]), .B (a[7]), .Y
       (mul_17_32_n_23));
  XNOR2X1 mul_17_32_g1584__8428(.A (b[5]), .B (a[4]), .Y
       (mul_17_32_n_22));
  CLKXOR2X1 mul_17_32_g1585__5526(.A (b[1]), .B (a[7]), .Y
       (mul_17_32_n_21));
  XNOR2X1 mul_17_32_g1586__6783(.A (b[3]), .B (a[4]), .Y
       (mul_17_32_n_20));
  XNOR2X1 mul_17_32_g1587__3680(.A (b[7]), .B (a[4]), .Y
       (mul_17_32_n_19));
  XNOR2X1 mul_17_32_g1588__1617(.A (b[7]), .B (a[2]), .Y
       (mul_17_32_n_18));
  XNOR2X1 mul_17_32_g1589__2802(.A (b[7]), .B (a[5]), .Y
       (mul_17_32_n_17));
  XNOR2X1 mul_17_32_g1590__1705(.A (b[7]), .B (a[1]), .Y
       (mul_17_32_n_16));
  XNOR2X1 mul_17_32_g1591__5122(.A (b[7]), .B (a[6]), .Y
       (mul_17_32_n_15));
  XNOR2X1 mul_17_32_g1592__8246(.A (b[7]), .B (a[3]), .Y
       (mul_17_32_n_14));
  XNOR2X1 mul_17_32_g1593__7098(.A (b[7]), .B (a[7]), .Y
       (mul_17_32_n_13));
  XNOR2X1 mul_17_32_g1594__6131(.A (b[3]), .B (b[4]), .Y
       (mul_17_32_n_12));
  NOR2XL mul_17_32_g1595__1881(.A (b[4]), .B (a[0]), .Y
       (mul_17_32_n_5));
  NOR2XL mul_17_32_g1596__5115(.A (b[2]), .B (a[0]), .Y
       (mul_17_32_n_4));
  NOR2XL mul_17_32_g1597__7482(.A (b[6]), .B (a[0]), .Y
       (mul_17_32_n_3));
  NOR2XL mul_17_32_g1598__4733(.A (mul_17_32_n_1), .B (mul_17_32_n_0),
       .Y (n_107));
  INVX1 mul_17_32_g1599(.A (b[0]), .Y (mul_17_32_n_1));
  INVX1 mul_17_32_g1600(.A (a[0]), .Y (mul_17_32_n_0));
  INVX20 g52(.A (n_243), .Y (n_210));
  INVX16 g2051(.A (n_259), .Y (n_216));
  NOR2X6 g57(.A (n_365), .B (en_mac), .Y (n_218));
  CLKAND2X6 g2055(.A (sum_sat[8]), .B (en_mac), .Y (n_221));
  INVX16 fopt28(.A (rst), .Y (n_231));
  INVX12 g2058(.A (n_236), .Y (n_237));
  NOR2X8 g2059(.A (n_234), .B (n_235), .Y (n_236));
  INVX3 g2060(.A (n_260), .Y (n_234));
  NAND2X8 g2061(.A (n_231), .B (n_224), .Y (n_235));
  NOR2X8 g16(.A (n_224), .B (n_242), .Y (n_243));
  NAND2X8 g2062(.A (n_240), .B (n_241), .Y (n_242));
  INVX20 fopt(.A (rst_mac), .Y (n_240));
  INVX16 fopt20(.A (rst), .Y (n_241));
  NOR3X8 g24(.A (rst), .B (rst_mac), .C (en_mac), .Y (n_259));
  INVX16 fopt2066(.A (rst_mac), .Y (n_260));
  INVX6 fopt2067(.A (rst), .Y (n_261));
  INVX20 fopt2068(.A (en_mac), .Y (n_224));
  AOI2BB1X4 g38(.A0N (n_218), .A1N (n_221), .B0 (n_315), .Y (n_266));
  CLKINVX2 fopt2070(.A (n_268), .Y (n_267));
  INVX2 fopt2072(.A (n_271), .Y (n_270));
  INVX2 fopt2074(.A (n_274), .Y (n_273));
  CLKINVX2 fopt2076(.A (n_277), .Y (n_276));
  CLKINVX2 fopt2078(.A (n_280), .Y (n_279));
  INVX2 fopt2080(.A (n_283), .Y (n_282));
  CLKINVX2 fopt2084(.A (n_289), .Y (n_288));
  INVX1 fopt2086(.A (n_292), .Y (n_291));
  INVX2 fopt2088(.A (n_295), .Y (n_294));
  CLKINVX2 fopt2090(.A (n_298), .Y (n_297));
  CLKINVX2 fopt2092(.A (n_301), .Y (n_300));
  INVX1 fopt2094(.A (n_304), .Y (n_303));
  CLKINVX2 fopt2096(.A (n_307), .Y (n_306));
  CLKINVX2 fopt2098(.A (n_310), .Y (n_309));
  CLKINVX2 fopt2100(.A (n_313), .Y (n_312));
  NAND2X4 g4(.A (n_261), .B (n_260), .Y (n_315));
  CLKBUFX2 fopt2103(.A (acc_out[7]), .Y (n_268));
  CLKBUFX2 fopt2105(.A (acc_out[9]), .Y (n_301));
  CLKBUFX2 fopt2107(.A (acc_out[10]), .Y (n_295));
  CLKBUFX2 fopt2109(.A (acc_out[11]), .Y (n_274));
  CLKBUFX2 fopt2111(.A (acc_out[12]), .Y (n_277));
  CLKBUFX2 fopt2113(.A (acc_out[13]), .Y (n_298));
  CLKBUFX2 fopt2115(.A (acc_out[14]), .Y (n_292));
  CLKBUFX2 fopt2117(.A (acc_out[15]), .Y (n_307));
  CLKBUFX2 fopt2119(.A (acc_out[4]), .Y (n_283));
  CLKBUFX2 fopt2121(.A (acc_out[0]), .Y (n_313));
  CLKBUFX2 fopt2123(.A (acc_out[2]), .Y (n_289));
  CLKBUFX2 fopt2125(.A (acc_out[1]), .Y (n_304));
  CLKBUFX2 fopt2127(.A (acc_out[5]), .Y (n_280));
  CLKBUFX2 fopt2129(.A (acc_out[3]), .Y (n_271));
  CLKBUFX2 fopt2131(.A (acc_out[6]), .Y (n_310));
  NOR2BX1 g2(.AN (b[1]), .B (b[0]), .Y (n_316));
  INVX8 fopt2167(.A (n_366), .Y (n_365));
  BUFX2 fopt2170(.A (acc_out[8]), .Y (n_366));
endmodule

