
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:17:08 IST (Feb 28 2026 09:47:08 UTC)

// Verification Directory fv/npu_fsm 

module npu_fsm(clk, rst, start, fifo_full, EN_COMP, EN_BUF_IN, EN_MAC,
     EN_ReLU, LATCH_RELU, FIFO_WR_EN, done);
  input clk, rst, start, fifo_full, EN_COMP;
  output EN_BUF_IN, EN_MAC, EN_ReLU, LATCH_RELU, FIFO_WR_EN, done;
  wire clk, rst, start, fifo_full, EN_COMP;
  wire EN_BUF_IN, EN_MAC, EN_ReLU, LATCH_RELU, FIFO_WR_EN, done;
  wire [2:0] current_state;
  wire n_0, n_5, n_22, n_52, n_60, n_69, n_70, n_73;
  wire n_74, n_78, n_80, n_81, n_91, n_93, n_94, n_98;
  wire n_100, n_101, n_102, n_103, n_106, n_107, n_108, n_113;
  wire n_124, n_142, n_144, n_145, n_156;
  assign FIFO_WR_EN = LATCH_RELU;
  assign EN_ReLU = EN_MAC;
  DFFRHQX8 \current_state_reg[0] (.RN (n_22), .CK (clk), .D (n_103), .Q
       (current_state[0]));
  DFFRHQX8 \current_state_reg[2] (.RN (n_22), .CK (clk), .D (n_81), .Q
       (current_state[2]));
  DFFRHQX4 \current_state_reg[1] (.RN (n_22), .CK (clk), .D (n_124), .Q
       (current_state[1]));
  NOR3X2 g721__3680(.A (current_state[1]), .B (current_state[2]), .C
       (n_69), .Y (EN_BUF_IN));
  NOR3X4 g722__1617(.A (current_state[0]), .B (current_state[2]), .C
       (n_108), .Y (EN_MAC));
  NAND2X2 g724__5122(.A (n_70), .B (n_142), .Y (n_5));
  INVX16 g732(.A (start), .Y (n_0));
  INVX1 g728(.A (rst), .Y (n_22));
  INVX20 fopt748(.A (EN_COMP), .Y (n_52));
  INVX8 g734_dup(.A (fifo_full), .Y (n_60));
  OAI21X4 g43(.A0 (n_107), .A1 (n_78), .B0 (n_80), .Y (n_81));
  AOI21X4 g45(.A0 (n_73), .A1 (n_74), .B0 (n_113), .Y (n_78));
  INVX8 fopt66(.A (current_state[0]), .Y (n_69));
  INVX16 fopt(.A (fifo_full), .Y (n_74));
  INVX2 g46(.A (n_100), .Y (n_80));
  CLKAND2X2 g95(.A (n_106), .B (n_142), .Y (n_91));
  INVX3 g99(.A (n_0), .Y (n_93));
  NOR2X8 g93(.A (n_5), .B (n_52), .Y (n_94));
  NOR3X6 g18(.A (current_state[2]), .B (n_108), .C (n_98), .Y
       (LATCH_RELU));
  INVX3 g19(.A (current_state[0]), .Y (n_98));
  NAND3BX4 g47(.AN (n_100), .B (n_101), .C (n_102), .Y (n_103));
  CLKAND2X2 g50(.A (n_73), .B (n_113), .Y (n_100));
  OAI21X4 g761(.A0 (n_70), .A1 (fifo_full), .B0 (n_91), .Y (n_101));
  NAND2X8 g49(.A (n_93), .B (n_94), .Y (n_102));
  INVX3 fopt2(.A (n_107), .Y (n_106));
  INVX8 fopt4(.A (current_state[1]), .Y (n_108));
  INVX2 fopt764(.A (n_142), .Y (n_113));
  OAI21X4 g85(.A0 (n_107), .A1 (n_60), .B0 (n_145), .Y (n_124));
  CLKBUFX4 fopt787(.A (n_156), .Y (n_142));
  INVX8 fopt788(.A (n_70), .Y (n_73));
  XNOR2X4 g789(.A (n_107), .B (n_144), .Y (n_145));
  NAND2X4 g790(.A (n_73), .B (n_142), .Y (n_144));
  NOR3X4 g805(.A (current_state[1]), .B (n_156), .C (current_state[0]),
       .Y (done));
  INVX8 g21(.A (current_state[2]), .Y (n_156));
  BUFX8 fopt807(.A (n_69), .Y (n_70));
  BUFX6 fopt815(.A (n_108), .Y (n_107));
endmodule

