
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 12:23:46 IST (Feb 28 2026 06:53:46 UTC)

// Verification Directory fv/npu_system_top 

module npu_system_top(clk, rst, start, wr_en, wr_addr, wr_data, DA, DB,
     DC, DD, done, D_OUT);
  input clk, rst, start, wr_en, wr_data;
  input [3:0] wr_addr;
  input [7:0] DA, DB, DC, DD;
  output done;
  output [7:0] D_OUT;
  wire clk, rst, start, wr_en, wr_data;
  wire [3:0] wr_addr;
  wire [7:0] DA, DB, DC, DD;
  wire done;
  wire [7:0] D_OUT;
  wire [15:0] acc_load_val;
  wire [2:0] SEL_OUT;
  wire [6:0] ACC_COUNT;
  wire ACC_EN, BIAS_EN, BYPASS_ReLU1, BYPASS_ReLU2, CTR_OUT, EN_COMP,
       EN_FIFO, FIFO_WR_EN;
  wire LAST_EN, OUT_DONE_ACC, OUT_DONE_OUT, OUT_LATCH_EN, RST_COMP,
       RST_FIFO, UNCONNECTED, UNCONNECTED0;
  wire fifo_empty, fifo_full, fifo_rd_en, n_0, n_1, n_2, n_14, n_15;
  assign acc_load_val[7] = 1'b0;
  assign acc_load_val[8] = 1'b0;
  assign acc_load_val[9] = 1'b0;
  assign acc_load_val[10] = 1'b0;
  assign acc_load_val[11] = 1'b0;
  assign acc_load_val[12] = 1'b0;
  assign acc_load_val[13] = 1'b0;
  assign acc_load_val[14] = 1'b0;
  assign acc_load_val[15] = 1'b0;
  downcounter_16bit u_ctr(.clk (clk), .rst (rst), .load (start),
       .en_cnt (ACC_EN), .load_value (acc_load_val), .CTR_OUT
       (CTR_OUT));
  fsm_acc u_fsm_acc(.clk (clk), .rst (rst), .EN_FSM (EN_COMP), .CTR_OUT
       (CTR_OUT), .OUT_DONE_FB (OUT_DONE_OUT), .ACC_EN (ACC_EN),
       .BIAS_EN (BIAS_EN), .LAST_EN (LAST_EN), .OUT_DONE
       (OUT_DONE_ACC));
  fsm_out u_fsm_out(.clk (clk), .rst (rst), .EN_OUT (OUT_DONE_ACC),
       .EN_ReLU1 (n_15), .EN_FIFO (EN_FIFO), .OUT_LATCH_EN
       (OUT_LATCH_EN), .FIFO_WR_EN (FIFO_WR_EN), .DONE (OUT_DONE_OUT));
  npu_core_top u_npu(.clk (clk), .rst (n_14), .DA (DA), .DB (DB), .DC
       (DC), .DD (DD), .EN_BUF_IN (ACC_EN), .EN_MAC (ACC_EN), .RST_MAC
       (rst), .SEL_BIAS1 (1'b0), .SEL_BIAS2 (1'b0), .EN_ReLU (n_15),
       .BYPASS_ReLU1 (BYPASS_ReLU1), .BYPASS_ReLU2 (BYPASS_ReLU2),
       .LATCH_RELU (OUT_LATCH_EN), .PISO_LOAD (OUT_LATCH_EN), .PISO_EN
       (1'b1), .FIFO_WR_EN (FIFO_WR_EN), .FIFO_RD_EN (fifo_rd_en),
       .SEL_OUT (SEL_OUT), .BIAS1 (16'b0), .BIAS2 (16'b0), .D_OUT
       (D_OUT), .FIFO_FULL (fifo_full), .FIFO_EMPTY (fifo_empty));
  ssfr u_ssfr(.clk (clk), .rst (rst), .wr_en (wr_en), .wr_addr
       (wr_addr), .wr_data (wr_data), .SEL_OUT (SEL_OUT), .BYPASS_ReLU1
       (BYPASS_ReLU1), .BYPASS_ReLU2 (BYPASS_ReLU2), .EN_COMP
       (EN_COMP), .RST_COMP (RST_COMP), .EN_FIFO (EN_FIFO), .RST_FIFO
       (RST_FIFO), .ACC_COUNT (ACC_COUNT), .SSFR_OUT (UNCONNECTED));
  INVX1 g97(.A (BYPASS_ReLU1), .Y (n_15));
  DFFRHQX4 done_r_reg(.RN (n_2), .CK (clk), .D (OUT_DONE_OUT), .Q
       (done));
  NAND2BX1 g98__2398(.AN (RST_COMP), .B (n_2), .Y (n_14));
  INVX1 g99(.A (rst), .Y (n_2));
  INVX1 g100(.A (fifo_empty), .Y (fifo_rd_en));
  OAI31X1 g133__5107(.A0 (ACC_COUNT[2]), .A1 (ACC_COUNT[1]), .A2 (n_1),
       .B0 (n_0), .Y (acc_load_val[0]));
  OR4X1 g134__6260(.A (ACC_COUNT[5]), .B (ACC_COUNT[6]), .C
       (ACC_COUNT[4]), .D (ACC_COUNT[3]), .Y (n_1));
  INVX1 g135(.A (ACC_COUNT[0]), .Y (n_0));
  BUFX2 g136(.A (ACC_COUNT[2]), .Y (acc_load_val[2]));
  BUFX2 g137(.A (ACC_COUNT[1]), .Y (acc_load_val[1]));
  BUFX2 g138(.A (ACC_COUNT[6]), .Y (acc_load_val[6]));
  BUFX2 g139(.A (ACC_COUNT[5]), .Y (acc_load_val[5]));
  BUFX2 g140(.A (ACC_COUNT[4]), .Y (acc_load_val[4]));
  BUFX2 g141(.A (ACC_COUNT[3]), .Y (acc_load_val[3]));
endmodule

