
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:09:56 IST (Feb 28 2026 09:39:56 UTC)

// Verification Directory fv/npu_core_top 

module npu_core_top(clk, rst, DA, DB, DC, DD, EN_BUF_IN, EN_MAC,
     RST_MAC, SEL_BIAS1, SEL_BIAS2, EN_ReLU, BYPASS_ReLU1,
     BYPASS_ReLU2, LATCH_RELU, PISO_LOAD, PISO_EN, FIFO_WR_EN,
     FIFO_RD_EN, SEL_OUT, BIAS1, BIAS2, D_OUT, FIFO_FULL, FIFO_EMPTY);
  input clk, rst, EN_BUF_IN, EN_MAC, RST_MAC, SEL_BIAS1, SEL_BIAS2,
       EN_ReLU, BYPASS_ReLU1, BYPASS_ReLU2, LATCH_RELU, PISO_LOAD,
       PISO_EN, FIFO_WR_EN, FIFO_RD_EN;
  input [7:0] DA, DB, DC, DD;
  input [2:0] SEL_OUT;
  input [15:0] BIAS1, BIAS2;
  output [7:0] D_OUT;
  output FIFO_FULL, FIFO_EMPTY;
  wire clk, rst, EN_BUF_IN, EN_MAC, RST_MAC, SEL_BIAS1, SEL_BIAS2,
       EN_ReLU, BYPASS_ReLU1, BYPASS_ReLU2, LATCH_RELU, PISO_LOAD,
       PISO_EN, FIFO_WR_EN, FIFO_RD_EN;
  wire [7:0] DA, DB, DC, DD;
  wire [2:0] SEL_OUT;
  wire [15:0] BIAS1, BIAS2;
  wire [7:0] D_OUT;
  wire FIFO_FULL, FIFO_EMPTY;
  wire [15:0] relu1_out;
  wire [15:0] relu2_out;
  wire [15:0] max_val;
  wire [7:0] max_idx;
  wire [7:0] piso_out;
  wire [7:0] fifo_dout;
  wire [7:0] DA_q;
  wire [7:0] DB_q;
  wire [7:0] DC_q;
  wire [7:0] DD_q;
  wire [7:0] r1_hi;
  wire [7:0] r1_lo;
  wire [7:0] r2_hi;
  wire [7:0] r2_lo;
  wire [15:0] mac1_out;
  wire [15:0] mac2_out;
  wire piso_busy, piso_done;
  auto_comparator2 u_comp(.clk (clk), .rst (rst), .en (LATCH_RELU), .a
       ({relu1_out[15:8], D_OUT}), .b (relu2_out), .max_val (max_val),
       .max_idx (max_idx));
  fifo_sync8_DEPTH128 u_fifo(.clk (clk), .rst (rst), .wr_en
       (FIFO_WR_EN), .rd_en (FIFO_RD_EN), .din (piso_out), .dout
       (fifo_dout), .full (FIFO_FULL), .empty (FIFO_EMPTY));
  input_buffer_4x8 u_inbuf(.clk (clk), .rst (rst), .en_buf (EN_BUF_IN),
       .DA (DA), .DB (DB), .DC (DC), .DD (DD), .DA_q (DA_q), .DB_q
       (DB_q), .DC_q (DC_q), .DD_q (DD_q));
  relu_stage_latch u_latch(.clk (clk), .rst (rst), .en (LATCH_RELU),
       .relu1 ({relu1_out[15:8], D_OUT}), .relu2 (relu2_out), .r1_hi
       (r1_hi), .r1_lo (r1_lo), .r2_hi (r2_hi), .r2_lo (r2_lo));
  mac_8x8_to_16 u_mac1(.clk (clk), .rst (rst), .en_mac (EN_MAC),
       .rst_mac (RST_MAC), .a (DA_q), .b (DB_q), .bias (BIAS1),
       .sel_bias (SEL_BIAS1), .acc_out (mac1_out));
  mac_8x8_to_16 u_mac2(.clk (clk), .rst (rst), .en_mac (EN_MAC),
       .rst_mac (RST_MAC), .a (DC_q), .b (DD_q), .bias (BIAS2),
       .sel_bias (SEL_BIAS2), .acc_out (mac2_out));
  piso_2x16_to_8 u_piso(.clk (clk), .rst (rst), .en (PISO_EN), .load
       (PISO_LOAD), .w1 ({relu1_out[15:8], D_OUT}), .w2 (relu2_out),
       .dout (piso_out), .busy (piso_busy), .done (piso_done));
  relu16 u_relu1(.clk (clk), .rst (rst), .EN_ReLU (EN_ReLU),
       .BYPASS_ReLU (BYPASS_ReLU1), .x_in (mac1_out), .x_out
       ({relu1_out[15:8], D_OUT}));
  relu16 u_relu2(.clk (clk), .rst (rst), .EN_ReLU (EN_ReLU),
       .BYPASS_ReLU (BYPASS_ReLU2), .x_in (mac2_out), .x_out
       (relu2_out));
endmodule

