
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:41:53 IST (Feb 28 2026 10:11:53 UTC)

// Verification Directory fv/output_mux 

module output_mux(sel, fifo_out, piso_out, comp_index, debug_out,
     D_OUT);
  input [2:0] sel;
  input [7:0] fifo_out, piso_out, comp_index, debug_out;
  output [7:0] D_OUT;
  wire [2:0] sel;
  wire [7:0] fifo_out, piso_out, comp_index, debug_out;
  wire [7:0] D_OUT;
  wire n_34, n_35, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56;
  NAND2X1 g689__2398(.A (n_43), .B (n_51), .Y (D_OUT[5]));
  NAND2X1 g690__5107(.A (n_44), .B (n_39), .Y (D_OUT[6]));
  NAND2X1 g691__6260(.A (n_40), .B (n_42), .Y (D_OUT[7]));
  NAND2X1 g694__4319(.A (n_54), .B (n_41), .Y (D_OUT[4]));
  NAND2X1 g695__8428(.A (n_46), .B (n_48), .Y (D_OUT[1]));
  NAND2X1 g692__5526(.A (n_56), .B (n_55), .Y (D_OUT[2]));
  NAND2X1 g696__6783(.A (n_37), .B (n_38), .Y (D_OUT[3]));
  NAND2X1 g693__3680(.A (n_45), .B (n_47), .Y (D_OUT[0]));
  AOI22XL g699__1617(.A0 (fifo_out[2]), .A1 (n_53), .B0
       (comp_index[2]), .B1 (n_52), .Y (n_56));
  AOI22XL g698__2802(.A0 (piso_out[2]), .A1 (n_50), .B0 (debug_out[2]),
       .B1 (n_49), .Y (n_55));
  AOI22XL g705__1705(.A0 (fifo_out[4]), .A1 (n_53), .B0
       (comp_index[4]), .B1 (n_52), .Y (n_54));
  AOI22XL g701__5122(.A0 (piso_out[5]), .A1 (n_50), .B0 (debug_out[5]),
       .B1 (n_49), .Y (n_51));
  AOI22XL g697__8246(.A0 (piso_out[1]), .A1 (n_50), .B0 (debug_out[1]),
       .B1 (n_49), .Y (n_48));
  AOI22XL g706__7098(.A0 (piso_out[0]), .A1 (n_50), .B0 (debug_out[0]),
       .B1 (n_49), .Y (n_47));
  AOI22XL g702__6131(.A0 (fifo_out[1]), .A1 (n_53), .B0
       (comp_index[1]), .B1 (n_52), .Y (n_46));
  AOI22XL g707__1881(.A0 (fifo_out[0]), .A1 (n_53), .B0
       (comp_index[0]), .B1 (n_52), .Y (n_45));
  AOI22XL g710__5115(.A0 (fifo_out[6]), .A1 (n_53), .B0
       (comp_index[6]), .B1 (n_52), .Y (n_44));
  AOI22XL g700__7482(.A0 (fifo_out[5]), .A1 (n_53), .B0
       (comp_index[5]), .B1 (n_52), .Y (n_43));
  AOI22XL g703__4733(.A0 (comp_index[7]), .A1 (n_52), .B0
       (debug_out[7]), .B1 (n_49), .Y (n_42));
  AOI22XL g709__6161(.A0 (piso_out[4]), .A1 (n_50), .B0 (debug_out[4]),
       .B1 (n_49), .Y (n_41));
  AOI22XL g708__9315(.A0 (fifo_out[7]), .A1 (n_53), .B0 (piso_out[7]),
       .B1 (n_50), .Y (n_40));
  AOI22XL g704__9945(.A0 (piso_out[6]), .A1 (n_50), .B0 (debug_out[6]),
       .B1 (n_49), .Y (n_39));
  AOI22XL g711__2883(.A0 (piso_out[3]), .A1 (n_50), .B0 (debug_out[3]),
       .B1 (n_49), .Y (n_38));
  AOI22XL g712__2346(.A0 (fifo_out[3]), .A1 (n_53), .B0
       (comp_index[3]), .B1 (n_52), .Y (n_37));
  NOR2XL g713__1666(.A (sel[1]), .B (n_35), .Y (n_50));
  NOR2BXL g714__7410(.AN (n_34), .B (sel[1]), .Y (n_53));
  NOR2BXL g715__6417(.AN (sel[1]), .B (n_35), .Y (n_49));
  AND2X1 g716__5477(.A (sel[1]), .B (n_34), .Y (n_52));
  NOR2XL g717__2398(.A (sel[0]), .B (sel[2]), .Y (n_34));
  NAND2BX1 g718__5107(.AN (sel[2]), .B (sel[0]), .Y (n_35));
endmodule

