
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:44:33 IST (Feb 28 2026 10:14:33 UTC)

// Verification Directory fv/piso_2x16_to_8 

module piso_2x16_to_8(clk, rst, en, load, w1, w2, dout, busy, done);
  input clk, rst, en, load;
  input [15:0] w1, w2;
  output [7:0] dout;
  output busy, done;
  wire clk, rst, en, load;
  wire [15:0] w1, w2;
  wire [7:0] dout;
  wire busy, done;
  wire [31:0] shreg;
  wire [1:0] cnt;
  wire n_1, n_6, n_10, n_12, n_13, n_18, n_20, n_24;
  wire n_25, n_26, n_28, n_29, n_31, n_33, n_35, n_37;
  wire n_41, n_42, n_43, n_44, n_45, n_49, n_51, n_53;
  wire n_64, n_65, n_69, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_171, n_172, n_183, n_187, n_192, n_1326, n_1974;
  wire n_1975, n_1976, n_1977, n_1979, n_1980, n_1981, n_1982, n_1983;
  wire n_1986, n_1990, n_1992, n_2007, n_2008, n_2011, n_2012, n_2015;
  wire n_2016, n_2035, n_2036, n_2037, n_2039, n_2048, n_2049, n_2053;
  wire n_2056, n_2058, n_2059, n_2060, n_2061, n_2062, n_2063, n_2064;
  wire n_2065, n_2067, n_2075, n_2076, n_2234, n_2235, n_2279, n_2282;
  wire n_2284, n_2285, n_2286, n_2287, n_2289, n_2291, n_2292, n_2296;
  wire n_2298, n_2299, n_2314, n_2331, n_2335, n_2372, n_2377, n_2380;
  wire n_2381, n_2384, n_2385, n_2400, n_2403, n_2420, n_2421, n_2424;
  wire n_2426, n_2436, n_2440, n_2441, n_2442, n_2443, n_2445, n_2446;
  wire n_2448, n_2452, n_2454, n_2456, n_2462, n_2463, n_2465, n_2466;
  wire n_2467, n_2494, n_2497, n_2498, n_2500, n_2502, n_2503, n_2504;
  wire n_2505, n_2521, n_2522, n_2523, n_2525, n_2526, n_2527, n_2528;
  wire n_2531, n_2532, n_2533, n_2534, n_2536, n_2537, n_2538, n_2539;
  wire n_2540, n_2541, n_2546, n_2547, n_2548, n_2549, n_2551, n_2552;
  wire n_2553, n_2554, n_2555, n_2556, n_2557, n_2558, n_2559, n_2560;
  wire n_2561, n_2565, n_2566, n_2567, n_2568, n_2569, n_2570, n_2571;
  wire n_2573, n_2574, n_2575, n_2576, n_2577, n_2578, n_2595, n_2596;
  wire n_2597, n_2598, n_2599, n_2600, n_2601, n_2602, n_2603, n_2604;
  wire n_2605, n_2606, n_2607, n_2608, n_2613, n_2614, n_2615, n_2616;
  wire n_2633, n_2634, n_2638, n_2640, n_2648, n_2649, n_2650, n_2651;
  wire n_2658, n_2659, n_2660, n_2661, n_2662, n_2667, n_2668, n_2676;
  wire n_2679;
  DFFHQX4 \shreg_reg[8] (.CK (clk), .D (n_2608), .Q (shreg[8]));
  DFFHQX4 \shreg_reg[9] (.CK (clk), .D (n_2016), .Q (shreg[9]));
  DFFHQX1 \shreg_reg[22] (.CK (clk), .D (n_2291), .Q (shreg[22]));
  DFFHQX1 \shreg_reg[23] (.CK (clk), .D (n_2286), .Q (shreg[23]));
  DFFHQX4 \shreg_reg[24] (.CK (clk), .D (n_2651), .Q (shreg[24]));
  DFFHQX1 \shreg_reg[25] (.CK (clk), .D (n_2456), .Q (shreg[25]));
  DFFHQX1 \shreg_reg[26] (.CK (clk), .D (n_2549), .Q (shreg[26]));
  DFFHQX1 \shreg_reg[27] (.CK (clk), .D (n_2676), .Q (shreg[27]));
  DFFHQX1 \shreg_reg[28] (.CK (clk), .D (n_183), .Q (shreg[28]));
  DFFHQX1 \shreg_reg[29] (.CK (clk), .D (n_187), .Q (shreg[29]));
  DFFHQX1 \shreg_reg[30] (.CK (clk), .D (n_2679), .Q (shreg[30]));
  DFFHQX1 \shreg_reg[31] (.CK (clk), .D (n_2668), .Q (shreg[31]));
  DFFHQX4 \shreg_reg[10] (.CK (clk), .D (n_2012), .Q (shreg[10]));
  DFFHQX4 \shreg_reg[11] (.CK (clk), .D (n_2008), .Q (shreg[11]));
  DFFHQX4 \shreg_reg[12] (.CK (clk), .D (n_2314), .Q (shreg[12]));
  DFFHQX4 \shreg_reg[13] (.CK (clk), .D (n_2467), .Q (shreg[13]));
  DFFHQX1 \shreg_reg[14] (.CK (clk), .D (n_2522), .Q (shreg[14]));
  DFFHQX1 \shreg_reg[15] (.CK (clk), .D (n_192), .Q (shreg[15]));
  DFFHQX4 \dout_reg[3] (.CK (clk), .D (n_2063), .Q (dout[3]));
  DFFHQX1 \shreg_reg[16] (.CK (clk), .D (n_2296), .Q (shreg[16]));
  DFFHQX2 \shreg_reg[17] (.CK (clk), .D (n_2289), .Q (shreg[17]));
  DFFHQX1 \shreg_reg[18] (.CK (clk), .D (n_2541), .Q (shreg[18]));
  DFFHQX1 \shreg_reg[19] (.CK (clk), .D (n_2298), .Q (shreg[19]));
  DFFHQX1 \shreg_reg[20] (.CK (clk), .D (n_2287), .Q (shreg[20]));
  DFFHQX1 \shreg_reg[21] (.CK (clk), .D (n_2377), .Q (shreg[21]));
  DFFHQX4 \dout_reg[1] (.CK (clk), .D (n_2056), .Q (dout[1]));
  DFFHQX4 \dout_reg[2] (.CK (clk), .D (n_2064), .Q (dout[2]));
  DFFHQX4 \dout_reg[0] (.CK (clk), .D (n_2058), .Q (dout[0]));
  DFFHQX4 \dout_reg[4] (.CK (clk), .D (n_2060), .Q (dout[4]));
  DFFHQX4 \dout_reg[5] (.CK (clk), .D (n_2061), .Q (dout[5]));
  DFFHQX4 \dout_reg[6] (.CK (clk), .D (n_2065), .Q (dout[6]));
  DFFHQX4 \dout_reg[7] (.CK (clk), .D (n_2059), .Q (dout[7]));
  DFFHQX4 \cnt_reg[1] (.CK (clk), .D (n_2062), .Q (cnt[1]));
  DFFHQX1 \shreg_reg[2] (.CK (clk), .D (n_165), .Q (shreg[2]));
  DFFHQX1 \shreg_reg[3] (.CK (clk), .D (n_169), .Q (shreg[3]));
  DFFHQX1 \shreg_reg[7] (.CK (clk), .D (n_167), .Q (shreg[7]));
  DFFHQX1 \shreg_reg[0] (.CK (clk), .D (n_166), .Q (shreg[0]));
  DFFHQX1 \shreg_reg[4] (.CK (clk), .D (n_171), .Q (shreg[4]));
  DFFHQX1 \shreg_reg[6] (.CK (clk), .D (n_168), .Q (shreg[6]));
  DFFHQX1 \shreg_reg[5] (.CK (clk), .D (n_172), .Q (shreg[5]));
  DFFHQX1 \shreg_reg[1] (.CK (clk), .D (n_164), .Q (shreg[1]));
  NAND2X2 g3094__7098(.A (n_2525), .B (n_2536), .Y (n_192));
  NAND2X2 g3070__4733(.A (n_2527), .B (n_2504), .Y (n_187));
  NAND2X2 g3071__2883(.A (n_2526), .B (n_2500), .Y (n_183));
  OAI21X4 g3120__5526(.A0 (n_26), .A1 (n_2523), .B0 (n_2553), .Y
       (n_172));
  OAI21X4 g3117__6783(.A0 (n_28), .A1 (n_2523), .B0 (n_2570), .Y
       (n_171));
  OAI21X4 g3115__3680(.A0 (n_35), .A1 (n_2523), .B0 (n_2279), .Y
       (n_169));
  OAI21X4 g3122__1617(.A0 (n_33), .A1 (n_2523), .B0 (n_2282), .Y
       (n_168));
  OAI21X4 g3125__2802(.A0 (n_51), .A1 (n_2523), .B0 (n_2285), .Y
       (n_167));
  OAI21X4 g3139__1705(.A0 (n_10), .A1 (n_2523), .B0 (n_2284), .Y
       (n_166));
  OAI21X4 g3144__5122(.A0 (n_44), .A1 (n_2523), .B0 (n_2571), .Y
       (n_165));
  OAI21X4 g3141__8246(.A0 (n_24), .A1 (n_2523), .B0 (n_2554), .Y
       (n_164));
  MDFFHQX4 \cnt_reg[0] (.CK (clk), .D0 (n_2452), .D1 (n_2616), .S0
       (cnt[0]), .Q (cnt[0]));
  DFFHQX8 busy_reg(.CK (clk), .D (n_2658), .Q (busy));
  NOR2X6 g3217__6161(.A (n_2662), .B (n_2076), .Y (n_69));
  OR2X1 g3218__2883(.A (cnt[1]), .B (n_64), .Y (n_65));
  INVX1 g3245(.A (dout[4]), .Y (n_53));
  INVX1 g3244(.A (shreg[7]), .Y (n_51));
  INVX1 g3279(.A (shreg[28]), .Y (n_49));
  INVX1 g3241(.A (shreg[30]), .Y (n_45));
  INVX1 g3248(.A (shreg[2]), .Y (n_44));
  INVX1 g3282(.A (dout[7]), .Y (n_43));
  INVX1 g3274(.A (shreg[27]), .Y (n_42));
  INVX1 g3270(.A (dout[6]), .Y (n_41));
  INVX1 g3239(.A (shreg[24]), .Y (n_37));
  INVX1 g3275(.A (shreg[3]), .Y (n_35));
  INVX1 g3273(.A (shreg[6]), .Y (n_33));
  INVX1 g3246(.A (shreg[29]), .Y (n_31));
  INVX1 g3280(.A (dout[3]), .Y (n_29));
  INVX1 g3277(.A (shreg[4]), .Y (n_28));
  INVX1 g3242(.A (shreg[5]), .Y (n_26));
  INVX1 g3240(.A (shreg[26]), .Y (n_25));
  INVX1 g3271(.A (shreg[1]), .Y (n_24));
  INVX1 g3247(.A (dout[2]), .Y (n_20));
  INVX1 g3276(.A (dout[0]), .Y (n_18));
  INVX1 g3272(.A (dout[1]), .Y (n_13));
  INVX1 g3281(.A (shreg[31]), .Y (n_12));
  INVX1 g3283(.A (shreg[0]), .Y (n_10));
  INVX1 g3278(.A (shreg[25]), .Y (n_6));
  INVX1 g3243(.A (dout[5]), .Y (n_1));
  INVX1 g3252(.A (cnt[0]), .Y (n_64));
  DFFHQX1 done_reg(.CK (clk), .D (n_2634), .Q (done));
  AOI21X4 g3138__4311(.A0 (shreg[10]), .A1 (n_2446), .B0 (n_2575), .Y
       (n_1326));
  CLKAND2X2 g3185__4908(.A (w1[8]), .B (n_1975), .Y (n_1976));
  CLKAND2X12 g3220__9945_dup4909(.A (n_1974), .B (load), .Y (n_1975));
  INVX20 fopt4910(.A (rst), .Y (n_1974));
  NOR2X8 g3171__4911(.A (n_1975), .B (n_2053), .Y (n_1977));
  CLKAND2X3 g3178__4913(.A (w2[8]), .B (n_1975), .Y (n_1979));
  CLKAND2X2 g3179__4914(.A (w1[11]), .B (n_1975), .Y (n_1980));
  CLKAND2X2 g3180__4915(.A (w2[9]), .B (n_1975), .Y (n_1981));
  CLKAND2X2 g3181__4916(.A (w1[13]), .B (n_1975), .Y (n_1982));
  CLKAND2X3 g3182__4917(.A (w2[7]), .B (n_1975), .Y (n_1983));
  CLKAND2X2 g3184__4919(.A (w1[10]), .B (n_2384), .Y (n_1986));
  CLKAND2X3 g3189__4923(.A (w1[9]), .B (n_2384), .Y (n_1990));
  CLKAND2X3 g3193__4925(.A (w2[3]), .B (n_2384), .Y (n_1992));
  NAND3X6 g40(.A (n_2037), .B (n_2537), .C (n_2007), .Y (n_2008));
  INVX4 g43(.A (n_1980), .Y (n_2007));
  NAND3X4 g4931(.A (n_2036), .B (n_2538), .C (n_2011), .Y (n_2012));
  INVX4 g4934(.A (n_1986), .Y (n_2011));
  NAND3X4 g4935(.A (n_2035), .B (n_2539), .C (n_2015), .Y (n_2016));
  INVX2 g4938(.A (n_1990), .Y (n_2015));
  NAND2X4 g4952(.A (shreg[9]), .B (n_2441), .Y (n_2035));
  NAND2X4 g4953(.A (shreg[10]), .B (n_2441), .Y (n_2036));
  NAND2X4 g4954(.A (shreg[11]), .B (n_2441), .Y (n_2037));
  OAI21X4 g3111__4956(.A0 (n_2292), .A1 (n_2441), .B0 (cnt[1]), .Y
       (n_2039));
  NAND2X6 g22(.A (n_2048), .B (n_69), .Y (n_2049));
  NAND2X4 g23(.A (en), .B (n_2633), .Y (n_2048));
  NOR2X6 g12(.A (n_2076), .B (n_2463), .Y (n_2053));
  OAI22X2 g3103__4965(.A0 (n_13), .A1 (n_1977), .B0 (n_6), .B1
       (n_2403), .Y (n_2056));
  OAI22X2 g3102__4967(.A0 (n_18), .A1 (n_1977), .B0 (n_37), .B1
       (n_2403), .Y (n_2058));
  OAI22X2 g3109__4969(.A0 (n_43), .A1 (n_1977), .B0 (n_12), .B1
       (n_2403), .Y (n_2059));
  OAI22X2 g3106__4970(.A0 (n_53), .A1 (n_1977), .B0 (n_49), .B1
       (n_2403), .Y (n_2060));
  OAI22X2 g3107__4971(.A0 (n_1), .A1 (n_1977), .B0 (n_31), .B1
       (n_2403), .Y (n_2061));
  OAI21X4 g3077__4972(.A0 (n_65), .A1 (n_2403), .B0 (n_2039), .Y
       (n_2062));
  OAI22X2 g3105__4973(.A0 (n_29), .A1 (n_1977), .B0 (n_42), .B1
       (n_2403), .Y (n_2063));
  OAI22X2 g3104__4974(.A0 (n_20), .A1 (n_1977), .B0 (n_25), .B1
       (n_2403), .Y (n_2064));
  OAI22X2 g3108__4975(.A0 (n_41), .A1 (n_1977), .B0 (n_45), .B1
       (n_2403), .Y (n_2065));
  NAND2X4 g32(.A (shreg[12]), .B (n_2443), .Y (n_2067));
  INVX8 g4984(.A (n_2075), .Y (n_2076));
  INVX16 fopt4038_dup4985(.A (rst), .Y (n_2075));
  AOI21X4 g3114__5103(.A0 (shreg[15]), .A1 (n_2452), .B0 (n_1983), .Y
       (n_2234));
  NAND2X4 g5104(.A (shreg[4]), .B (n_2452), .Y (n_2235));
  NAND2X2 g5139(.A (w1[3]), .B (n_2384), .Y (n_2279));
  NAND2X2 g5142(.A (w1[6]), .B (n_2384), .Y (n_2282));
  NAND2X2 g5144(.A (w1[0]), .B (n_2384), .Y (n_2284));
  NAND2X2 g5145(.A (w1[7]), .B (n_2384), .Y (n_2285));
  OAI2BB1X4 g5146(.A0N (shreg[23]), .A1N (n_2443), .B0 (n_2234), .Y
       (n_2286));
  OAI2BB1X4 g5147(.A0N (shreg[20]), .A1N (n_2436), .B0 (n_2400), .Y
       (n_2287));
  OAI2BB1X4 g5149(.A0N (shreg[17]), .A1N (n_2436), .B0 (n_2502), .Y
       (n_2289));
  OAI2BB1X4 g5151(.A0N (shreg[22]), .A1N (n_2441), .B0 (n_2381), .Y
       (n_2291));
  NOR3BX4 g5152(.AN (n_64), .B (load), .C (rst), .Y (n_2292));
  OAI2BB1X4 g5155(.A0N (shreg[16]), .A1N (n_2436), .B0 (n_2497), .Y
       (n_2296));
  OAI2BB1X4 g5157(.A0N (shreg[19]), .A1N (n_2436), .B0 (n_2533), .Y
       (n_2298));
  AOI21X4 g5160(.A0 (shreg[22]), .A1 (n_2446), .B0 (n_2555), .Y
       (n_2299));
  NAND3X4 g5173(.A (n_2552), .B (n_2067), .C (n_2235), .Y (n_2314));
  CLKAND2X3 g45(.A (w2[10]), .B (n_1975), .Y (n_2331));
  CLKAND2X3 g5193(.A (w2[11]), .B (n_1975), .Y (n_2335));
  NOR2X8 g3219__9315_dup4081_dup5220(.A (load), .B (rst), .Y (n_2372));
  OAI2BB1X4 g5222(.A0N (shreg[21]), .A1N (n_2436), .B0 (n_2532), .Y
       (n_2377));
  NOR2X4 g35(.A (n_2380), .B (n_2560), .Y (n_2381));
  CLKAND2X2 g36(.A (n_2421), .B (n_2667), .Y (n_2380));
  CLKAND2X3 g31(.A (w2[0]), .B (n_2384), .Y (n_2385));
  CLKAND2X12 g5225(.A (n_1974), .B (load), .Y (n_2384));
  AOI21X4 g3142__5232(.A0 (shreg[12]), .A1 (n_2454), .B0 (n_2577), .Y
       (n_2400));
  INVX20 fopt5235(.A (n_2454), .Y (n_2403));
  CLKAND2X6 g5254(.A (n_2420), .B (en), .Y (n_2421));
  INVX16 fopt5255(.A (rst), .Y (n_2420));
  INVX20 fopt5258(.A (rst), .Y (n_2424));
  CLKINVX20 fopt5197_dup(.A (rst), .Y (n_2426));
  CLKAND2X12 g3208__5267(.A (n_2660), .B (n_2372), .Y (n_2436));
  CLKAND2X12 g3208__4037_dup5270(.A (n_2661), .B (n_2440), .Y (n_2441));
  NOR2X8 g3219__9315_dup5271(.A (load), .B (rst), .Y (n_2440));
  CLKAND2X12 g5272(.A (n_2661), .B (n_2442), .Y (n_2443));
  NOR2X8 g3219__9315_dup4951_dup(.A (load), .B (rst), .Y (n_2442));
  CLKAND2X12 g5274(.A (n_2445), .B (n_2421), .Y (n_2446));
  NOR2X8 g5275(.A (load), .B (n_2662), .Y (n_2445));
  NOR2X6 g5230_dup(.A (load), .B (n_2662), .Y (n_2448));
  CLKAND2X12 g3209__4120_dup5278(.A (n_2448), .B (n_2598), .Y (n_2452));
  CLKAND2X12 g3209__4120_dup4964_dup5281(.A (n_2445), .B (n_2596), .Y
       (n_2454));
  NAND2X4 g5282(.A (n_2521), .B (n_2505), .Y (n_2456));
  NOR2X4 g11(.A (n_2662), .B (n_2462), .Y (n_2463));
  NAND3X6 g5288(.A (n_2531), .B (n_2465), .C (n_2466), .Y (n_2467));
  NAND2X4 g39(.A (shreg[13]), .B (n_2436), .Y (n_2465));
  INVX4 g5289(.A (n_1982), .Y (n_2466));
  AOI21X4 g5308(.A0 (shreg[8]), .A1 (n_2567), .B0 (n_2385), .Y
       (n_2497));
  NOR2X8 g3212__4076_dup4284_dup5310(.A (n_2662), .B (load), .Y
       (n_2494));
  AOI21X4 g5312(.A0 (shreg[19]), .A1 (n_2567), .B0 (n_2335), .Y
       (n_2498));
  AOI21X4 g3123__5314(.A0 (shreg[20]), .A1 (n_2567), .B0 (n_2573), .Y
       (n_2500));
  AOI21X4 g3137__5315(.A0 (shreg[9]), .A1 (n_2565), .B0 (n_2559), .Y
       (n_2502));
  AOI21X4 g3136__5316(.A0 (shreg[23]), .A1 (n_2565), .B0 (n_2578), .Y
       (n_2503));
  AOI21X4 g3124__5317(.A0 (shreg[21]), .A1 (n_2565), .B0 (n_2556), .Y
       (n_2504));
  AOI21X4 g5318(.A0 (shreg[17]), .A1 (n_2565), .B0 (n_1981), .Y
       (n_2505));
  NAND2X4 g5326(.A (shreg[25]), .B (n_2616), .Y (n_2521));
  OAI2BB1X4 g5329(.A0N (shreg[14]), .A1N (n_2616), .B0 (n_2534), .Y
       (n_2522));
  CLKINVX12 g5330(.A (n_2616), .Y (n_2523));
  NAND2X4 g3157__5331(.A (shreg[15]), .B (n_2614), .Y (n_2525));
  NAND2X4 g3159__5332(.A (shreg[28]), .B (n_2614), .Y (n_2526));
  NAND2X4 g3161__5333(.A (shreg[29]), .B (n_2614), .Y (n_2527));
  NAND2X4 g5334(.A (shreg[5]), .B (n_2604), .Y (n_2531));
  NOR2X8 g3212__4076_dup5336(.A (n_2662), .B (load), .Y (n_2528));
  AOI21X4 g5338(.A0 (shreg[13]), .A1 (n_2604), .B0 (n_2576), .Y
       (n_2532));
  AOI21X4 g5339(.A0 (shreg[11]), .A1 (n_2604), .B0 (n_1992), .Y
       (n_2533));
  AOI21X4 g3134__5340(.A0 (shreg[6]), .A1 (n_2604), .B0 (n_2561), .Y
       (n_2534));
  AOI21X4 g3135__5341(.A0 (shreg[7]), .A1 (n_2602), .B0 (n_2558), .Y
       (n_2536));
  NAND2X4 g5342(.A (shreg[3]), .B (n_2602), .Y (n_2537));
  NAND2X4 g5343(.A (shreg[2]), .B (n_2602), .Y (n_2538));
  NAND2X4 g5344(.A (shreg[1]), .B (n_2602), .Y (n_2539));
  NAND2X2 g5345(.A (n_2540), .B (n_1326), .Y (n_2541));
  NAND2X4 g3(.A (shreg[18]), .B (n_2436), .Y (n_2540));
  NAND3X6 g5350(.A (n_2546), .B (n_2547), .C (n_2548), .Y (n_2549));
  NAND2X4 g41(.A (shreg[26]), .B (n_2443), .Y (n_2546));
  NAND2X6 g42(.A (shreg[18]), .B (n_2567), .Y (n_2547));
  INVX3 g5351(.A (n_2331), .Y (n_2548));
  NAND2X4 g5353(.A (w1[12]), .B (n_2551), .Y (n_2552));
  CLKAND2X12 g3220__5354(.A (n_2568), .B (load), .Y (n_2551));
  NAND2X4 g5355(.A (w1[5]), .B (n_2551), .Y (n_2553));
  NAND2X4 g5356(.A (w1[1]), .B (n_2551), .Y (n_2554));
  CLKAND2X3 g3172__5357(.A (w2[14]), .B (n_2551), .Y (n_2555));
  CLKAND2X6 g3202__5358(.A (w2[13]), .B (n_2551), .Y (n_2556));
  CLKAND2X3 g3200__5359(.A (w1[15]), .B (n_2557), .Y (n_2558));
  CLKAND2X6 g3220__4993_dup(.A (load), .B (n_2568), .Y (n_2557));
  CLKAND2X3 g3173__5360(.A (w2[1]), .B (n_2557), .Y (n_2559));
  CLKAND2X3 g3197__5361(.A (w2[6]), .B (n_2557), .Y (n_2560));
  CLKAND2X3 g3198__5362(.A (w1[14]), .B (n_2557), .Y (n_2561));
  CLKAND2X12 g5295_dup5365(.A (n_2494), .B (n_2638), .Y (n_2565));
  CLKAND2X12 g5369(.A (n_2494), .B (n_2566), .Y (n_2567));
  NOR2X8 g5311_dup(.A (n_2462), .B (n_2640), .Y (n_2566));
  INVX20 fopt4038_dup4321_dup5370(.A (rst), .Y (n_2568));
  NAND2X4 g5371(.A (w1[4]), .B (n_2569), .Y (n_2570));
  CLKAND2X12 g3220__4986_dup5372(.A (load), .B (n_2568), .Y (n_2569));
  NAND2X2 g5373(.A (w1[2]), .B (n_2569), .Y (n_2571));
  CLKAND2X3 g3203__5375(.A (w2[12]), .B (n_2569), .Y (n_2573));
  CLKAND2X3 g3175__5376(.A (w2[2]), .B (n_2574), .Y (n_2575));
  CLKAND2X6 g3220__4986_dup_dup(.A (load), .B (n_2568), .Y (n_2574));
  CLKAND2X3 g3207__5377(.A (w2[5]), .B (n_2574), .Y (n_2576));
  CLKAND2X3 g3199__5378(.A (w2[4]), .B (n_2574), .Y (n_2577));
  CLKAND2X3 g3174__5379(.A (w2[15]), .B (n_2574), .Y (n_2578));
  CLKAND2X6 g3213__4077_dup5256_dup5393(.A (n_2595), .B (en), .Y
       (n_2596));
  INVX16 fopt4929_dup5394(.A (rst), .Y (n_2595));
  CLKAND2X6 g3213__4077_dup5395(.A (n_2597), .B (en), .Y (n_2598));
  INVX16 fopt4929_dup5280_dup(.A (rst), .Y (n_2597));
  CLKAND2X12 g7_dup5396(.A (n_2528), .B (n_2601), .Y (n_2602));
  NOR2X8 g5397(.A (n_2599), .B (n_2600), .Y (n_2601));
  INVX20 fopt5398(.A (en), .Y (n_2599));
  INVX16 fopt5399(.A (n_2424), .Y (n_2600));
  CLKAND2X12 g5400(.A (n_2528), .B (n_2603), .Y (n_2604));
  NOR2X8 g5337_dup(.A (n_2599), .B (n_2600), .Y (n_2603));
  NAND3X4 g5401(.A (n_2605), .B (n_2606), .C (n_2607), .Y (n_2608));
  NAND2X4 g34(.A (shreg[8]), .B (n_2443), .Y (n_2605));
  NAND2X4 g33(.A (shreg[0]), .B (n_2446), .Y (n_2606));
  INVX4 g5402(.A (n_1976), .Y (n_2607));
  CLKAND2X12 g3208__4221_dup5265_dup5406(.A (n_2660), .B (n_2613), .Y
       (n_2614));
  NOR2X6 g3219__9315_dup4081_dup5076_dup5407(.A (load), .B (rst), .Y
       (n_2613));
  CLKAND2X12 g3208__4221_dup5408(.A (n_2660), .B (n_2615), .Y (n_2616));
  NOR2X8 g3219__9315_dup4081_dup5076_dup5328_dup(.A (load), .B (rst),
       .Y (n_2615));
  CLKAND2X3 g9(.A (n_2633), .B (n_2454), .Y (n_2634));
  AND2X1 g10(.A (cnt[0]), .B (cnt[1]), .Y (n_2633));
  CLKAND2X6 g5428(.A (n_2426), .B (en), .Y (n_2638));
  INVX16 fopt5429(.A (en), .Y (n_2462));
  INVX6 g13(.A (n_2426), .Y (n_2640));
  NAND3X4 g5437(.A (n_2648), .B (n_2649), .C (n_2650), .Y (n_2651));
  NAND2X4 g5438(.A (shreg[24]), .B (n_2441), .Y (n_2648));
  NAND2X4 g5439(.A (shreg[16]), .B (n_2446), .Y (n_2649));
  INVX3 g44(.A (n_1979), .Y (n_2650));
  NAND2BX4 g5441(.AN (n_2569), .B (n_2049), .Y (n_2658));
  NAND2X8 g3215__5442(.A (n_2659), .B (en), .Y (n_2660));
  BUFX2 g1(.A (busy), .Y (n_2659));
  NAND2X8 g3215__5073_dup5443(.A (busy), .B (en), .Y (n_2661));
  INVX12 g5445(.A (busy), .Y (n_2662));
  NOR3BX4 g2(.AN (shreg[14]), .B (n_2662), .C (load), .Y (n_2667));
  OAI2BB1X4 g5449(.A0N (shreg[31]), .A1N (n_2443), .B0 (n_2503), .Y
       (n_2668));
  OAI2BB1X4 g5457(.A0N (shreg[27]), .A1N (n_2443), .B0 (n_2498), .Y
       (n_2676));
  OAI2BB1X4 g5460(.A0N (shreg[30]), .A1N (n_2441), .B0 (n_2299), .Y
       (n_2679));
endmodule

