
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:46:10 IST (Feb 28 2026 10:16:10 UTC)

// Verification Directory fv/relu16 

module relu16(clk, rst, EN_ReLU, BYPASS_ReLU, x_in, x_out);
  input clk, rst, EN_ReLU, BYPASS_ReLU;
  input [15:0] x_in;
  output [15:0] x_out;
  wire clk, rst, EN_ReLU, BYPASS_ReLU;
  wire [15:0] x_in;
  wire [15:0] x_out;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_23;
  wire n_24, n_517, n_519, n_526, n_530, n_533, n_534, n_535;
  wire n_536, n_538, n_539, n_540, n_541, n_544, n_546, n_547;
  wire n_548, n_549, n_550, n_641, n_644, n_645, n_646, n_647;
  wire n_649, n_650, n_651, n_685, n_687, n_688, n_689, n_690;
  wire n_691, n_1095;
  DFFHQX1 \x_out_reg[14] (.CK (clk), .D (n_649), .Q (x_out[14]));
  DFFHQX1 \x_out_reg[12] (.CK (clk), .D (n_538), .Q (x_out[12]));
  DFFHQX1 \x_out_reg[8] (.CK (clk), .D (n_647), .Q (x_out[8]));
  DFFHQX1 \x_out_reg[0] (.CK (clk), .D (n_535), .Q (x_out[0]));
  DFFHQX1 \x_out_reg[7] (.CK (clk), .D (n_644), .Q (x_out[7]));
  DFFHQX1 \x_out_reg[11] (.CK (clk), .D (n_540), .Q (x_out[11]));
  DFFHQX1 \x_out_reg[6] (.CK (clk), .D (n_541), .Q (x_out[6]));
  DFFHQX1 \x_out_reg[5] (.CK (clk), .D (n_534), .Q (x_out[5]));
  DFFHQX1 \x_out_reg[13] (.CK (clk), .D (n_536), .Q (x_out[13]));
  DFFHQX1 \x_out_reg[10] (.CK (clk), .D (n_650), .Q (x_out[10]));
  DFFHQX1 \x_out_reg[4] (.CK (clk), .D (n_539), .Q (x_out[4]));
  DFFHQX1 \x_out_reg[3] (.CK (clk), .D (n_533), .Q (x_out[3]));
  DFFHQX1 \x_out_reg[9] (.CK (clk), .D (n_645), .Q (x_out[9]));
  DFFHQX1 \x_out_reg[2] (.CK (clk), .D (n_646), .Q (x_out[2]));
  DFFHQX1 \x_out_reg[1] (.CK (clk), .D (n_651), .Q (x_out[1]));
  DFFHQX1 \x_out_reg[15] (.CK (clk), .D (n_24), .Q (x_out[15]));
  NOR2X6 g1566__1881(.A (n_1095), .B (n_23), .Y (n_24));
  NAND2X4 g1567__7482(.A (x_in[15]), .B (BYPASS_ReLU), .Y (n_23));
  BUFX2 g1577(.A (x_in[10]), .Y (n_16));
  BUFX2 g1571(.A (x_in[4]), .Y (n_15));
  BUFX2 g1572(.A (x_in[8]), .Y (n_14));
  BUFX2 g1573(.A (x_in[2]), .Y (n_13));
  BUFX2 g1583(.A (x_in[3]), .Y (n_12));
  BUFX2 g1574(.A (x_in[9]), .Y (n_11));
  BUFX2 g1575(.A (x_in[13]), .Y (n_10));
  BUFX2 g1584(.A (x_in[1]), .Y (n_8));
  BUFX2 g1585(.A (x_in[6]), .Y (n_7));
  BUFX2 g1589(.A (x_in[11]), .Y (n_6));
  BUFX2 g1587(.A (x_in[12]), .Y (n_5));
  BUFX2 g1582(.A (x_in[0]), .Y (n_4));
  BUFX2 g1588(.A (x_in[14]), .Y (n_3));
  BUFX2 g1576(.A (x_in[7]), .Y (n_2));
  BUFX2 g1586(.A (x_in[5]), .Y (n_1));
  INVX20 g2031(.A (BYPASS_ReLU), .Y (n_517));
  INVX20 g2024_dup(.A (BYPASS_ReLU), .Y (n_519));
  INVX12 g2016_dup2038(.A (EN_ReLU), .Y (n_526));
  CLKAND2X6 g1556__2040(.A (n_12), .B (n_546), .Y (n_533));
  NAND2X8 g1569__2042(.A (x_in[15]), .B (n_517), .Y (n_530));
  CLKAND2X6 g1561__2044(.A (n_1), .B (n_546), .Y (n_534));
  CLKAND2X6 g1552__2045(.A (n_4), .B (n_546), .Y (n_535));
  CLKAND2X6 g1562__2046(.A (n_10), .B (n_546), .Y (n_536));
  CLKAND2X6 g1555__2047(.A (n_5), .B (n_544), .Y (n_538));
  CLKAND2X6 g1563__2048(.A (n_15), .B (n_544), .Y (n_539));
  CLKAND2X6 g1557__2049(.A (n_6), .B (n_544), .Y (n_540));
  CLKAND2X6 g1564__2050(.A (n_7), .B (n_544), .Y (n_541));
  CLKAND2X12 g1565__2020_dup2051(.A (n_550), .B (n_530), .Y (n_544));
  CLKAND2X12 g1565__2054(.A (n_548), .B (n_530), .Y (n_546));
  NOR2X8 g1570__1896_dup2043_dup2055(.A (rst), .B (n_547), .Y (n_548));
  INVX20 g2056(.A (EN_ReLU), .Y (n_547));
  NOR2X8 g1570__1896_dup2057(.A (rst), .B (n_549), .Y (n_550));
  INVX20 g2053_dup(.A (EN_ReLU), .Y (n_549));
  CLKAND2X6 g1558__2139(.A (n_2), .B (n_685), .Y (n_644));
  NAND2X8 g1569__1899_dup2141(.A (x_in[15]), .B (n_519), .Y (n_641));
  CLKAND2X6 g1560__2143(.A (n_11), .B (n_685), .Y (n_645));
  CLKAND2X6 g1554__2144(.A (n_13), .B (n_685), .Y (n_646));
  CLKAND2X6 g1559__2145(.A (n_14), .B (n_685), .Y (n_647));
  CLKAND2X6 g1551__2146(.A (n_3), .B (n_687), .Y (n_649));
  CLKAND2X6 g1550__2147(.A (n_16), .B (n_687), .Y (n_650));
  CLKAND2X6 g1549__2148(.A (n_8), .B (n_687), .Y (n_651));
  CLKAND2X12 g1565__5115_dup2174(.A (n_691), .B (n_641), .Y (n_685));
  CLKAND2X12 g1565__5115_dup2033_dup2177(.A (n_689), .B (n_641), .Y
       (n_687));
  NOR2X8 g1570__2142_dup2178(.A (rst), .B (n_688), .Y (n_689));
  INVX20 g2016_dup2035_dup2179(.A (EN_ReLU), .Y (n_688));
  NOR2X8 g1570__2180(.A (rst), .B (n_690), .Y (n_691));
  INVX20 g2016_dup2035_dup2176_dup(.A (EN_ReLU), .Y (n_690));
  OR2X6 g2(.A (rst), .B (n_526), .Y (n_1095));
endmodule

