
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 28 2026 15:21:23 IST (Feb 28 2026 09:51:23 UTC)

// Verification Directory fv/ssfr 

module ssfr(clk, rst, wr_en, wr_addr, wr_data, SEL_OUT, BYPASS_ReLU1,
     BYPASS_ReLU2, EN_COMP, RST_COMP, EN_FIFO, RST_FIFO, ACC_COUNT,
     SSFR_OUT);
  input clk, rst, wr_en, wr_data;
  input [3:0] wr_addr;
  output [2:0] SEL_OUT;
  output BYPASS_ReLU1, BYPASS_ReLU2, EN_COMP, RST_COMP, EN_FIFO,
       RST_FIFO;
  output [6:0] ACC_COUNT;
  output [15:0] SSFR_OUT;
  wire clk, rst, wr_en, wr_data;
  wire [3:0] wr_addr;
  wire [2:0] SEL_OUT;
  wire BYPASS_ReLU1, BYPASS_ReLU2, EN_COMP, RST_COMP, EN_FIFO, RST_FIFO;
  wire [6:0] ACC_COUNT;
  wire [15:0] SSFR_OUT;
  wire n_26, n_41, n_117, n_118, n_139, n_144, n_146, n_147;
  wire n_153, n_154, n_174, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_190, n_191, n_220, n_228, n_259, n_263, n_265;
  wire n_266, n_281, n_282, n_335, n_336, n_337, n_365, n_399;
  wire n_425, n_446, n_447, n_448, n_449, n_450, n_454, n_456;
  wire n_457, n_460, n_461, n_480, n_481, n_482, n_483, n_496;
  wire n_498, n_500, n_503, n_505, n_519, n_520, n_521, n_522;
  wire n_523, n_524, n_525, n_526, n_527, n_528, n_530, n_531;
  assign SSFR_OUT[0] = ACC_COUNT[0];
  assign SSFR_OUT[1] = ACC_COUNT[1];
  assign SSFR_OUT[2] = ACC_COUNT[2];
  assign SSFR_OUT[3] = ACC_COUNT[3];
  assign SSFR_OUT[4] = ACC_COUNT[4];
  assign SSFR_OUT[5] = ACC_COUNT[5];
  assign SSFR_OUT[6] = ACC_COUNT[6];
  assign SSFR_OUT[7] = RST_FIFO;
  assign SSFR_OUT[8] = EN_FIFO;
  assign SSFR_OUT[9] = RST_COMP;
  assign SSFR_OUT[10] = EN_COMP;
  assign SSFR_OUT[11] = BYPASS_ReLU2;
  assign SSFR_OUT[12] = BYPASS_ReLU1;
  assign SSFR_OUT[13] = SEL_OUT[0];
  assign SSFR_OUT[14] = SEL_OUT[1];
  assign SSFR_OUT[15] = SEL_OUT[2];
  SDFFRHQX2 \ssfr_reg[1] (.RN (n_41), .CK (clk), .D (ACC_COUNT[1]), .SE
       (n_503), .SI (wr_data), .Q (ACC_COUNT[1]));
  SDFFRHQX2 \ssfr_reg[11] (.RN (n_41), .CK (clk), .D (BYPASS_ReLU2),
       .SE (n_118), .SI (wr_data), .Q (BYPASS_ReLU2));
  SDFFRHQX2 \ssfr_reg[3] (.RN (n_41), .CK (clk), .D (ACC_COUNT[3]), .SE
       (n_144), .SI (wr_data), .Q (ACC_COUNT[3]));
  SDFFRHQX2 \ssfr_reg[15] (.RN (n_41), .CK (clk), .D (SEL_OUT[2]), .SE
       (n_449), .SI (wr_data), .Q (SEL_OUT[2]));
  SDFFRHQX2 \ssfr_reg[5] (.RN (n_41), .CK (clk), .D (ACC_COUNT[5]), .SE
       (n_505), .SI (wr_data), .Q (ACC_COUNT[5]));
  SDFFSHQX4 \ssfr_reg[7] (.SN (n_41), .CK (clk), .D (RST_FIFO), .SE
       (n_220), .SI (wr_data), .Q (RST_FIFO));
  SDFFRHQX2 \ssfr_reg[8] (.RN (n_41), .CK (clk), .D (EN_FIFO), .SE
       (n_482), .SI (wr_data), .Q (EN_FIFO));
  SDFFRHQX4 \ssfr_reg[14] (.RN (n_41), .CK (clk), .D (SEL_OUT[1]), .SE
       (n_524), .SI (wr_data), .Q (SEL_OUT[1]));
  SDFFSHQX4 \ssfr_reg[9] (.SN (n_41), .CK (clk), .D (RST_COMP), .SE
       (n_185), .SI (wr_data), .Q (RST_COMP));
  SDFFRHQX2 \ssfr_reg[10] (.RN (n_41), .CK (clk), .D (EN_COMP), .SE
       (n_26), .SI (wr_data), .Q (EN_COMP));
  SDFFRHQX2 \ssfr_reg[12] (.RN (n_41), .CK (clk), .D (BYPASS_ReLU1),
       .SE (n_461), .SI (wr_data), .Q (BYPASS_ReLU1));
  SDFFSHQX2 \ssfr_reg[13] (.SN (n_41), .CK (clk), .D (SEL_OUT[0]), .SE
       (n_266), .SI (wr_data), .Q (SEL_OUT[0]));
  SDFFRHQX2 \ssfr_reg[0] (.RN (n_41), .CK (clk), .D (ACC_COUNT[0]), .SE
       (n_481), .SI (wr_data), .Q (ACC_COUNT[0]));
  SDFFRHQX4 \ssfr_reg[6] (.RN (n_41), .CK (clk), .D (ACC_COUNT[6]), .SE
       (n_447), .SI (wr_data), .Q (ACC_COUNT[6]));
  SDFFRHQX2 \ssfr_reg[2] (.RN (n_41), .CK (clk), .D (ACC_COUNT[2]), .SE
       (n_282), .SI (wr_data), .Q (ACC_COUNT[2]));
  SDFFRHQX2 \ssfr_reg[4] (.RN (n_41), .CK (clk), .D (ACC_COUNT[4]), .SE
       (n_425), .SI (wr_data), .Q (ACC_COUNT[4]));
  NOR2X4 g8314__1617(.A (n_281), .B (n_528), .Y (n_26));
  INVX1 g8349(.A (rst), .Y (n_41));
  NOR2X6 g2(.A (n_117), .B (n_281), .Y (n_118));
  NAND3X8 g8417(.A (wr_addr[0]), .B (wr_en), .C (wr_addr[3]), .Y
       (n_117));
  NOR3X6 g35(.A (n_139), .B (n_228), .C (n_523), .Y (n_144));
  INVX8 fopt49(.A (wr_addr[0]), .Y (n_139));
  NAND2X8 g40(.A (wr_en), .B (n_146), .Y (n_147));
  INVX16 fopt50(.A (wr_addr[3]), .Y (n_146));
  INVX12 fopt16(.A (wr_addr[2]), .Y (n_153));
  INVX16 fopt(.A (wr_addr[1]), .Y (n_154));
  INVX6 fopt8437(.A (n_457), .Y (n_174));
  NOR3X8 g8439(.A (n_180), .B (n_183), .C (n_184), .Y (n_185));
  INVX6 fopt8440(.A (wr_addr[0]), .Y (n_180));
  NAND2X8 g8441(.A (n_181), .B (n_182), .Y (n_183));
  INVX12 fopt45(.A (wr_addr[1]), .Y (n_181));
  NAND2X8 g8442(.A (wr_en), .B (wr_addr[3]), .Y (n_184));
  NOR2X8 g9(.A (wr_addr[2]), .B (n_190), .Y (n_191));
  INVX20 fopt8443(.A (wr_addr[1]), .Y (n_190));
  NOR4X8 g8465(.A (n_153), .B (n_154), .C (n_139), .D (n_147), .Y
       (n_220));
  NAND2X8 g8470(.A (wr_addr[1]), .B (n_182), .Y (n_228));
  INVX20 fopt8471(.A (wr_addr[2]), .Y (n_182));
  INVX12 fopt8401_dup8499(.A (wr_addr[3]), .Y (n_259));
  NAND3X8 g8502(.A (wr_addr[3]), .B (wr_en), .C (wr_addr[0]), .Y
       (n_263));
  NOR2X6 g8503(.A (n_265), .B (n_174), .Y (n_266));
  NAND3X8 g43_dup(.A (wr_addr[3]), .B (wr_en), .C (wr_addr[0]), .Y
       (n_265));
  NOR3X8 g8511(.A (n_500), .B (n_530), .C (n_281), .Y (n_282));
  INVX12 g27(.A (n_191), .Y (n_281));
  INVX6 fopt42(.A (wr_addr[2]), .Y (n_335));
  NAND2X8 g37(.A (wr_en), .B (n_336), .Y (n_337));
  INVX20 fopt8552(.A (wr_addr[0]), .Y (n_336));
  NAND2X6 g8574(.A (n_259), .B (wr_en), .Y (n_365));
  INVX16 fopt8401_dup8463_dup8593(.A (wr_addr[3]), .Y (n_399));
  NOR2X4 g25(.A (n_460), .B (n_498), .Y (n_425));
  NOR3X6 g8628(.A (n_500), .B (n_446), .C (n_365), .Y (n_447));
  NAND2X8 g8629(.A (wr_addr[2]), .B (wr_addr[1]), .Y (n_446));
  NOR2X6 g8630(.A (n_448), .B (n_263), .Y (n_449));
  NAND2X4 g8553_dup(.A (wr_addr[2]), .B (wr_addr[1]), .Y (n_448));
  INVX16 fopt8632(.A (wr_addr[3]), .Y (n_450));
  INVX16 fopt8635(.A (wr_addr[1]), .Y (n_454));
  CLKAND2X6 g8338__8636(.A (n_456), .B (wr_addr[2]), .Y (n_457));
  INVX16 fopt47_dup(.A (wr_addr[1]), .Y (n_456));
  NOR3X6 g8639(.A (n_500), .B (n_531), .C (n_460), .Y (n_461));
  NAND2X8 g8640(.A (wr_addr[2]), .B (n_454), .Y (n_460));
  NOR2X4 g8653(.A (n_480), .B (n_498), .Y (n_481));
  OR2X6 g8654(.A (wr_addr[2]), .B (wr_addr[1]), .Y (n_480));
  NOR2X4 g8655(.A (n_480), .B (n_528), .Y (n_482));
  OR2X6 g8435_dup(.A (wr_addr[2]), .B (wr_addr[1]), .Y (n_483));
  INVX20 fopt8662(.A (wr_addr[0]), .Y (n_496));
  NAND3X8 g8663(.A (wr_en), .B (n_399), .C (n_496), .Y (n_498));
  INVX6 g8664(.A (n_336), .Y (n_500));
  NOR2X6 g8666(.A (n_483), .B (n_522), .Y (n_503));
  NOR2X4 g8316__8668(.A (n_460), .B (n_520), .Y (n_505));
  NAND3X8 g36_dup8675(.A (wr_addr[0]), .B (wr_en), .C (n_519), .Y
       (n_520));
  INVX20 fopt8676(.A (wr_addr[3]), .Y (n_519));
  NAND3X8 g8677(.A (wr_addr[0]), .B (wr_en), .C (n_521), .Y (n_522));
  INVX20 fopt8591_dup8678(.A (wr_addr[3]), .Y (n_521));
  NAND2X6 g8679(.A (wr_en), .B (n_519), .Y (n_523));
  NOR4X8 g8680(.A (n_521), .B (n_154), .C (n_335), .D (n_337), .Y
       (n_524));
  NAND2X8 g8681(.A (n_496), .B (n_527), .Y (n_528));
  NOR2X8 g8567_dup8682(.A (n_525), .B (n_526), .Y (n_527));
  INVX20 fopt8623_dup8683(.A (wr_en), .Y (n_525));
  INVX16 fopt8438_dup8684(.A (wr_addr[3]), .Y (n_526));
  NAND2X6 g8686(.A (n_450), .B (wr_en), .Y (n_530));
  NAND2X8 g8687(.A (wr_en), .B (wr_addr[3]), .Y (n_531));
endmodule

